<option>[EQT] LICEU DR. FRANCISCO FATO CFFM-CAÁLA</option>
<option>[EQT] INSTITUTO POLITÉCNICO PROFESSOR ESTÉVÃO NHIME CFFM- CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº42 MARIA DA CONCEIÇÃO WIMBO PINTO CFFM-CLA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº40 PE FREDERICO PILARTES DA SILVA CFFM CLA</option>
<option>[EQT] COMPLEXO ESCOLAR EFETIKILO - MUANGUNJA - CAALA</option>
<option>[EQT] COLÉGIO JOÃO BAPTISTA CHICOMO CFFM- CAALA</option>
<option>[EQT] COLÉGIO COMANDANTE EVARISTO CATUMBELA CFFM- CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 245 - EPWACHA - CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 18A - LUA CHEIA - CAALA</option>
<option>[EQT] COLÉGIO Nº 256 - CACHINDONGO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 217 - SONOLOTI CAALA</option>
<option>[EQT] COLEGIO Nº 256. - CACHINDONGO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº249 - 17 DE SETEMBRO CAALA</option>
<option>[EQT] COMPLEXO ESCOLAR MENSAGEIRO DO AMOR DIVINO - CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 255 - CALILONGUE CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 173 - SACAALA II CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº26 - NDONGUA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 21 - ANTÓNIO AGOSTINHO NETO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº11 CAALA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 243 - CUÍMA CAALA</option>
<option>[EQT] INSTITUTO POLITÉCNICA Nº 257 - CATATA- CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº102 CANGOMBE CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 84 - CHIVOLA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 7 CHIPA - CHIWYA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 55 CHILAMBO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº5 MANGUMBALA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 47 - CAWAIALA I CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 36 - LONGUEVE CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 231 - CAMBALOMBO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 227 - LOMUE CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 211 - CACHINDONGO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 178 - CAMUNDA-CALUI CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 16 COMPÃO CAALA</option>
<option>[EQT] ESCOLA DE MAGISTÉRIO TEOFILO DUARTE DO CUÍMA CAALA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 88 CDTE NZAJI  - CATATA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 9 LENHA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº79 CASSUPI II CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº77 LUPILI CAALA</option>
<option>[EQT] MAGISTÉRIO DA CAÁLA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 149 SACANDUMBO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº144 SACAMBUTA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 124 ELIAS CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 118 CASSONGUE CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº73 CAPUNJE CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 68 - CAIAMBO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 63 - CHICULUNDUNDA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 24 - CANTÃO PAHULA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº14 NACANDIANGO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº134 CHALONDO CAALA</option>
<option>[EQT] COMPLEXO ESCOLAR COMPARTICIPADO CALULU CAALA</option>
<option>[EQT] COLÉGIO CDTE MARIEN N´GOUABI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 94 EQUEVO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº32 - CALOMANDA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº. 220 - MBOA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 160 - CASSENDJE CAALA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DE EDUCAÇÃO DA CAÁLA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 4 C.R.C III CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 3 CATELENGA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 232 - CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 201 - GUERENGUE CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 20 - CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº183 - MANDI CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 175A - GOVI - CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N.º136 SACALINGÃ CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N.º126 SUNGUETE CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 115 CAWÉ CAALA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 88 CDTE NZAJI - CATATA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº74 CHICALA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 6 CANGOLA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 258 - ACOLONGONJO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº239 - CANDONGUI CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 219 - EVILA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 164 - FÁTIMA-PÔE CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 223 - MISSÃO DA CAMUNDA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 12 CHANDENDA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº111 CUTAMBELA CAALA</option>
<option>[EQT] COLÉGIO Nº246 - CALENGA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 17 CASSOCO ALDEIA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRA Nº70 - NGUMBE-NGALILEIYA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 59 KAPALI CAALA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 11 DE NOVEMBRO CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 52 - MANDELE CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº18 - C.R.C - I CAALA</option>
<option>[EQT] LICEU DA CAÁLA</option>
<option>[EQT] COMPLEXO ESCOLAR 4 DE ABRIL CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº43 - KM 25 CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº39 - CATENGUENHA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 167 - ETOTO CAALA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 1 - AUGUSTO NGANGULA CAALA</option>
<option>[EQT] COLÉGIO Nº 244 - CAALA</option>
<option>[EQT] COLÉGIO CDTE MARIA TONHA PEDALÉ - CAÁLA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº57 CANOA CAALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 48 DAMASCO CAALA</option>
