<option>[EQT] COMPLEXO ESCOLAR N. 29 ANTONIO MUNGUENDE - BIBALA</option>
<option>[EQT] ESCOLA PRIMARIA N. 28 SACO MALANGUECA - BIBALA</option>
<option>[EQT] INSTITUTO TÉCNICO AGRÁRIO DO KAPANGOMBE N. 19 - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 08 - SANTO AGOSTINHO - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 24 - MUEVANGO - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 27-MUHONDA I-BIBALA</option>
<option>[EQT] COLÉGIO N. 21 - ENGº JOSÉ EDUARDO DOS SANTOS - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 04 - CAMPO - DE - AVIAÇÃO - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 11. CAITOU-BIBALA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 25 - FRANCISCO CATUMA - BIBALA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DA BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 12 - MANUEL MESQUITA LEMOS - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 13 - MUVANDA - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 22 - PUPA 2 - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 02 - KAMUPAPA - BIBALA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 16 - MUNHINO - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 01 - MUCUA - WOVAHONA - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 05 - MUHONDA II - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 15 - CARACULO - BIBALA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 14 - MANGUEIRAS - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 03 - QUILEMBA - VELHA - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 10 - LOLA - BIBALA</option>
<option>[EQT] MAGISTÉRIO N. 20 - 5 DE OUTUBRO -BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 07 - 1 DE FEVEREIRO - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 06 - TATAILA - BIBALA</option>
<option>[EQT] LICEU N. 26 - JOÃO MARIA TYINDUMBILI - BIBALA</option>
<option>[EQT] ESCOLA POLITÉCNICA N. 18 - MAHITA - BIBALA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 23 TCHINANGA FINA - BIBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 09 - AMARO CORREIA ALMEIDA - BIBALA</option>
<option>[EQT] COLÉGIO N. 17 - SANTINA - BIBALA</option>
