<option>[EQT] ESCOLA PRIMÁRIA N. 3 DO NAGINGA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 6 DO SAIMBUANDA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 2 DO ASSENTAMENTO - CAMBA NGUJI</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO LOVUA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 17 DO LÓVUA</option>
<option>[EQT] COMPLEXO ESCOLAR DO SATAMBUE</option>
<option>[EQT] COMPLEXO ESCOLAR DO TXILONGO</option>
