<option>[EQT] ESCOLA PRIMÁRIA BG 5143 - 8 DE MARÇO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG - 5191 - MISSÃO DE KAPUSSO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5190 - 10 DE DEZEMBRO - BABAERA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5037 - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5138 - 2 DE MARÇO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5127 - HAVEMOS DE VOLTAR - EBANGA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5192 - GALILEIA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5151 - CHICAVA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5120 - KAPUMUMU - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5125 - MISSÃO DA KAWANGA - GANDA</option>
<option>[EQT] ESCOLA PRIMARIA BG 5096 - 28 DE AGOSTO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5046 - 17 DE SETEMBRO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5043 - 22 DE NOVEMBRO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5307 - SIMA-CHIVOLE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5023 - DEOLINDA RODRIGUES - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5079 - EKUIKUI II - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5101 - KAMAKA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5167 - KALUYUA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5177 -  SUSSANGUE - GANDA</option>
<option>[EQT] CENTRO DE RECURSO BG 5008 - EDUCAÇÃO ESPECIAL - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5203 - LUWE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5153 - CACHISSEQUELELE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5025 - CDTE. KWENHA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5205 - LOMUPA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5000 - PISI - GANDA </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5026 - ATUQUI - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5009 - 11 DE NOVEMBRO - BABEARA -GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5073 - KANDJOLA - GANDA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 5003 - JOÃO PAULO II - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5161 - NGOLO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5076 - DUMBO OLIVEIRA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5087 - LUNDUNGO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5159 -  KATANHA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5078 - KALULU - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5036 - CHICUMA-SISALANA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5059 - KAHONDIO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5172 - CAMBULA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5157 - KASSENJE-EPALANGA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5031 - CDTE KASSANJE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5306 - BAIRRO DA FRANÇA - GANDA</option>
<option>[EQT] COLÉGIO BG 5007 - CDTE. KUSSI - GANDA</option>
<option>[EQT] INSTITUTO POLITÉCNICO BG 5188 - GANDA</option>
<option>[EQT] COLÉGIO BG 5182 - MAJOR SAIDY VIEIRA MINGAS - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5018 - SENDJE KAMBAYA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5135 - 17 DE SETEMBRO - EBANGA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5015 - 11 DE NOVEMBRO - EBANGA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5178 - LUSSIPA I - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5117 - LOMBUNDJE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5074 - LUMWE II BG - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5179 - LONGONGO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5061 - EMALANGA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5119 - KALANDI 2º - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5166 - HULUNGUMBE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5150 - KATATO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5004 - TCHITAU - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5137 - 10 DE DEZEMBRO - EBANGA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5196 - CACHIQUENGUE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5308 - JUNTA DE CAFÉ - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5082 - KAKOMBO NDUNTI - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5077 - REI MANDUME - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5109 - CATAPI - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5126 - KALUSIPA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5152 - CHICOSSI - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5169 - CAICUVE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5045 - CAHAMBOTO - GANDA</option>
<option>[EQT] COLÉGIO BG 5202 - DR. ANTÓNIO AGOSTINHO NETO - GANDA</option>
<option>[EQT] COLÉGIO BG 5181 - 14 DE ABRIL - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5021 - CDTE. JIKA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5024 - CERÂMICA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5019 - KALUNDO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5017 - MARTIRES DE CATENGUE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5130 - CDTE. KASSANJI - EBANGA - GANDA</option>
<option>[EQT] COLÉGIO BG 5183 - 17 DE SETEMBRO - GANDA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 5012 - 4 DE JANEIRO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5115 - TENDAMOKO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5042 - PIO XII - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5171 - SACUONGA - GANDA</option>
<option>[EQT] LICEU BG 5309 - 12 DE MARÇO - ALTO CATUMBELA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5165 - CAMANGA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5170 - CANGUNDO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5014 - CAPALA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5195 - VOYE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5098 - ACARANGOLO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5030 - CHICANDULA - GANDA </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5063 - DONGOROCA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5002 - LUTA CONTINUA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5072 - 1º DE MAIO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5131 - 1 DE JUNHO - GANDA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 5204 - NOSSA SRA DE LASSALET - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5016 - MISSÃO EVANGÉLICA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5071 - HAVEMOS DE VOLTAR - BABAERA- GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5092 - SANDULA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5122 - KALANDI 3º - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5168 - KAIENJE - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5145 - EKUIKUI II - EBANGA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5189 - CDTE. DANGEREUX -  BABAERA - GANDA</option>
<option>[EQT] LICEU BG 5186 - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5022 - 21 DE OUTUBRO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5001 - REI MANDUME - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5244 - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5129 - CDTE DANGEREUX - ENABGA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5085 - BOTA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5139 - EKOVONGO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5099 - CATAMBA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5163 - SANZALA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5060 - KASSOLA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5158 - KASENDJE KWILO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5102 - UKUKU - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5065 - SÓLIO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5084 - KAHIVA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5176 - CASSISSA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5069 - CDTE. CHEGUEVARA - BABAERA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5020 - 10 DE DEZEMBRO - GANDA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DA GANDA</option>
<option>[EQT] MAGISTÉRIO BG 5187 - GANDA</option>
<option>[EQT] COLÉGIO BG 5147 - ETALA - GANDA</option>
<option>[EQT] COLÉGIO BG 5089 - 22 DE NOVEMBRO - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5141 - 22 DE NOVEMBRO - EBANGA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5081 - KATUSOLA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5133 - HOJI-YA-HENDA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5198 - CAVAVA CAYELA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5050 - KOTINDI - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5041 - ULILA 3º - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5011 - SÃO FRANCISCO DE ASSIS - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5142 - SANGUNGU - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5160 - MARTIR DE CHICUMA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5136 - TCHIKALA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5118 - KALOMBINDA II - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5149 - CATALA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5010 - DEOLINDA RODRIGUES BABAERA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5194 - CHILESSA - GANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 5162 - NIMA - GANDA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 5148 - 4 DE ABRIL - GANDA</option>
<option>[EQT] COLÉGIO BG 5207 - 5 DE OUTUBRO DA GANDA</option>
