<option>[EQT] MAGISTÉRIO DO DUNDO</option>
<option>[EQT] ESCOLA DO ENSINO PRIMÁRIO N. 11 - CHITATO</option>
<option>[EQT] INSTITUTO MÉDIO PELITÉCINICO DO DUNDO - LUNDA NORTE</option>
<option>[EQT] GABINETE PROVINCIAL DA EDUCAÇÃO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO TXINGUVO - DUNDO</option>
<option>[EQT] COLÉGIO DO CAMAQUENZO I</option>
<option>[EQT] COMPLEXO ESCOLAR DELEGADO EUSÉBIO NELSON</option>
<option>[EQT] ESCOLA DO ENS. SECUNDÁRIO N. 6 - CHITATO</option>
<option>[EQT] ESCOLA DO ENSINO PRIMÁRIO N. 9 - CHITATO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO ENSINO ESPECIAL DO DUNDO</option>
<option>[EQT] COMPLEXO ESCOLAR DO SAMACACA</option>
<option>[EQT] MAGISTÉRIO PRIMÁRIO 11 DE NOVEMBRO DO CHITATO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 1 DO CHITATO</option>
<option>[EQT] LICEU DO DUNDO</option>
<option>[EQT] COLÉGIO N. 13 DO DUNDO</option>
<option>[EQT] COMPLEXO ESCOLAR DO CAXINDE</option>
<option>[EQT] ESCOLA DO ENSINO PRIMÁRIO N. 4 - CHITATO</option>
<option>[EQT] COMPLEXO ESCOLAR DO CARINHENGA</option>
<option>[EQT] COMPLEXO ESCOLAR DO MUANGUVO</option>
<option>[EQT] ESCOLA DO EN. PRIM E I CÍCLO DO ENSINO SECUNDÁRIO - CHITATO</option>
<option>[EQT] COLÉGIO DO BOM DEUS</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CHITATO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 02 DO RITENDA - DUNDO</option>
<option>[EQT] COMPLEXO ESCOLAR EX - PGFA - DUNDO</option>
<option>[EQT] COMPLEXO ESCOLAR N.14 EX - CAVALOS - DUNDO</option>
<option>[EQT] COLÉGIO DO SANTO ANTÓNIO DO CHITATO</option>
<option>[EQT] ESCOLA PRIMÁRIA CLAÚDIO FRANCISCO POULLAR PLACE (CATÓLICA)</option>
<option>[EQT] COLÉGIO DO SACHINDONGO SACHINDONGO</option>
<option>[EQT] COMPLEXO ESCOLAR 4 DE JULHO DO BAIRRO AEROPORTO - DUNDO</option>
<option>[EQT] ESCOLA DO ENSINO PRIMÁRIO N. 5 - CHITATO</option>
<option>[EQT] ESCOLA DO ENS. SECUNDÁRIO N. 7 - CHITATO</option>
<option>[EQT] INSTITUTO TÉCNICO DE SAÚDE DA LUNDA - NORTE</option>
