<option>[EQT] ESCOLA PRIMÁRIA NOSSA SENHORA DAS MERCÊS - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CUNDA - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR FEMININO SANTA MADALENA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO YABI - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MÊZMO - CABINDA</option>
<option>[EQT] SECRETARIA PROVINCIAL DE EDUCAÇÃO DE CABINDA</option>
<option>[EQT] COMPLEXO ESC. MISSIONÁRIO D. PAULINO FERNANDO MADECA - CABINDA</option>
<option>[EQT] COLÉGIO CABASSANGO - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR SANTA CATARINA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LOMBO - LOMBO II - CABINDA</option>
<option>[EQT] LICEU DE CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR DE CHINSUÁ - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAIO - CABINDA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA A VITÓRIA É CERTA - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR DE IZÔNGOLO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAIO - CALIADO - CABINDA</option>
<option>[EQT] INSTITUTO POLITÉCNO DE CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR N.º 223 CDTE GIKA - CABINDA</option>
<option>[EQT] COLÉGIO LUVASSA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BUMELAMBUTO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO LUCOLA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHINGUNDO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SIADEDE - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR MISSIONÁRIA BAUVECA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA AMÍLCAR CABRAL - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR CAIO - CONGO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BUNGO FUANA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TANDO - ZINZE - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE FORTALEZA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BUCO - NGOIO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIMBOLO - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR ANEXO AO MAGISTÉRIO - CABINDA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NHOBO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA AUGUSTO NGANGULA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TAMBA - CABINDA</option>
<option>[EQT] LICEU N.º 304 - DUQUE DE CHIAZI - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR DE LOMBO - LOMBO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BISSASSANHA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIPITA - LIAMBO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA SÃO JOSÉ DE LIMANO - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR MISSIONÁRIO BRAZITA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CHINZAZI - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA MPUNZI NZAU - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR SÃO JOSÉ DE CLUNY - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR MBANDA NGÓ BILOLO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO MBUCO - CABINDA</option>
<option>[EQT] MAGISTÉRIO DE CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR MISSIONÁRIO LUCULA ZENZE - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE FÚTILA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO SIMINDELE - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA N.º 176 SIMULAMBUCO I - CABINDA</option>
<option>[EQT] MED GABINETE DE INSPECCAO ESCOLAR CABIND</option>
<option>[EQT] ESCOLA PRIMÁRIA DO SENDE - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO NTUMBA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA HOJI - YA - HENDA - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR DE CHIBODO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ZANGOIO - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR DE SIAMA - CABINDA</option>
<option>[EQT] COLÉGIO CHIWECA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CHIWECA - CABINDA</option>
<option>[EQT] INSTITUTO POLITÉCNICO DE ADMINISTRAÇÃO E GESTÃO DE CABASSANGO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SÃO VICENTE - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHINGANGA - CABINDA</option>
<option>[EQT] INSTITUTO TÉCNICO DE SAÚDE DE CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR DO YABI - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA CDTE DANGEREUX - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA 4 DE FEVEREIRO - CABINDA</option>
<option>[EQT] INSTITUTO POLITÉCNICO DE CHIAZI - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE IMANHA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CABASSANGO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SÃO PEDRO - COTE - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA CDTE VALÓDIA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SIAMAZI - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHINDENDE - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NDUNGO - BUBA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA SAYDI - MINGAS - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO LOMBE - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CHIBODO - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR SIMULAMBUCO II - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA SAGRADA ESPERANÇA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHINGUINGUILI - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LELO - CABINDA</option>
<option>[EQT] COLÉGIO SAYDI MINGAS - CABINDA</option>
<option>[EQT] COLÉGIO BARÃO PUNA - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR MISSIONÁRIO MAMÃ MUXIMA - CABINDA</option>
<option>[EQT] INSTITITUTO POLITÉCNICO JOÃO PAULO II - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MALEMBO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TALI BECA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA JOAQUIM KAPANGO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA NGIMBI - NKONKO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA PATRICE LUMUMBA - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LUVASSA - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR DE CHINGA - CABINDA</option>
<option>[EQT] COLÉGIO BUCO - MAZI - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SUBANTANDO - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR BOM DEUS - CABINDA</option>
<option>[EQT] COLÉGIO LUÍS GOMES SAMBO - CABINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIOBO - CABINDA</option>
<option>[EQT] COMPLEXO ESCOLAR GENERAL PEDALÉ - CABINDA</option>
