<option>[EQT] ESCOLA PRIMÁRIA N. 5 DO SAMBO</option>
<option>[EQT] ESCOLA PRIMARIA Nº63 DE ESSOKO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMARIA Nº67 DO NHANI CHICALA CHOLOHANGA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 5 DO SAMBO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº43 DE CAWE EPALANGA - CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº49 DE OMBALA CALUCO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº37 CHIMUANGA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº56 CALÃ CHICALA CHOLOHANGA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº78 OMBALA CALEMBE CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº39 CHISSAQUELA MUNDA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº18 DE CATUCO - CHICALA CHOLOHANGA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº4 DO MBAVE - CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 22 DE LIAMBAMBI CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº21 DE EPOMBA VILEMBA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº16 DE CANDUMBO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº72 CHICALA CHOLOSSAPI CHICALA CHOLOHANGA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 10 KANDUMBO - CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 68 SAMBONGO CHICALA CHOLOHANGA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº10 KANDUMBO - CHICALA CHOLOHANGA</option>
<option>[EQT] COLÉGIO Nº55 DE SAMBOTO - CHICALA CHOLOHANGA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 4 DO MBAVE CHICALA CHOLOHANGA </option>
<option>[EQT] ESCOLA PRIMÁRIA Nº26 DE ULONDO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº73 DE CHOLOLO - CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 69 DE CATEWA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 13 DEOLINDA RODRIGUES CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº17 DE CANGOMBE CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMARIA Nº76 DE  ETUNDA I - CHICALA CHOLOHANGA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 33 VALENTINO SAMBO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº62 CHIPESSE CHICALA CHOLOHANGA</option>
<option>[EQT] COLÉGIO Nº77 DE ESSAQUE  CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº20 DE DONGOLÓCUA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 71 DE CATETE CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMARIA Nº59 DE KANGANDA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº27 DE USSINDA CATOTA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº25 DE TALULUA I CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº54 SASSOMA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº65 DE MOTA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº64 DE HUNGULO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº40 DE CHIVEMBE CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº34 CAMBINDA III CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº60 CATUTU CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº24 DE SATIAVALA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº50 OMBALA CAPULE CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 45 DE LOMBUNDI CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 201 DE ESSAQUE CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº9 DE CHIPULI CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº36 DE CHILOVA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº3 DE BOAS ÁGUAS CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº46 MISSÃO CATÓLICA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 23 DE SANJIOMBUIO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº52 OMBALA NDELE CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº38 CHISSAQUELA CATIMBA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº35 CANGOTI CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº42 DE CHONGOLOLA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº51 OMBALA CAVATA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº18 DE CANJUNGUE CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N´12 DE CANATA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 1 - AUGUSTO NGANGULA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº61 CHILALA - CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº29 DE VINHENI CHICALA CHOLOHANGA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº33 VALENTINO SAMBO CHICALA CHOLOHANGA</option>
<option>[EQT] COLÉGIO Nº76 DE SACAMBUIO - TCHICALA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº28 DE USSINDA VILEMBA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº48 DE NUNDA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº47 DE NGONDO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº66 NDALA NULA CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº74 DE MBULO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº58 DE CALUEIO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº41 CHIWISSI CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº70 CAPUTO CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº14 CALILONGUE CHICALA CHOLOHANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 15 DE CAMBUIO BAIXO CHICALA CHOLOHANGA</option>
