<option>[EQT] ESCOLA PRIMÁRIA N. 2 - DIOLINDA RODRIGUES - QUIRIMA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº1 - XINDINGO - QUIRIMA</option>
<option>[EQT] COLÉGIO N. 5 - HOJI-YA-HENDA - QUIRIMA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº3 -SAUTAR - QUIRIMA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE QUIRIMA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº4-QUIRIMA</option>
