<option>[EQT] COMPLEXO ESCOLAR Nº 15 - REI NGOLA KILUANJE - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 4 - 17 DE SETEMBRO - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 1 - MAJOR KAHANGULO - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 8 - 4 DE FEVEREIRO - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 14 - NZINGA MBANDI  - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 6 - HOJI-YA-HENDA - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 2 - JOSÉ DO TELHADO - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 11 - COMANDANTE MULEKA - MUCARI</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 7 - SANTA TERESINHA - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 12 - 28 DE AGOSTO - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 10 - 1º DE MAIO  - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 3 - COMANDANTE BULA MATADE - MUCARI</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO MUCARI  </option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 5 - 11 DE NOVEMBRO - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 9 - 1 DE JUNHO - MUCARI</option>
<option>[EQT] ESCOLA PRIMÁRIA, Nº 13 - DEOLINDA RODRIGUES - MUCARI</option>
