<option data-provincia="Lunda-Norte">Cambulo</option>
<option data-provincia="Lunda-Norte">Chitato</option>
<option data-provincia="Lunda-Norte">Cuilo</option>
<option data-provincia="Lunda-Norte">Caungula</option>
<option data-provincia="Lunda-Norte">Cuango</option>
<option data-provincia="Lunda-Norte">Lubalo</option>
<option data-provincia="Lunda-Norte">Capenda Camulemba</option>
<option data-provincia="Lunda-Norte">Lóvua</option>
<option data-provincia="Lunda-Norte">Lucapa</option>
<option data-provincia="Lunda-Norte">Xá Muteba</option>
