<option>[EQT] ESCOLA PRIMÁRIA N. 1202 - VELHO YANGO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 1203 - COMANDANTE SEKOUTURÉ</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 1201 - BANZA QUILOMBO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 1204 - CAVUNGA</option>
<option>[EQT] REPARTICAO MUNICIPAL DA EDUCAÇAO DE GONGUEMBO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 1205 - CAMAME</option>
<option>[EQT] LICEU N. 1206 KALA KIZWA - GONGUEMBO</option>
