<option>[EQT] COMPLEXO ESCOLAR N. 21 CCM1 - 4 DE ABRIL - LIKUWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 02 CCM1 - 11 DE NOVEMBRO</option>
<option>[EQT] LICEU N. 22 CCM1 - MAVINGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 14 CCM1 MWENE KAPILU</option>
<option>[EQT] COMPLEXO ESCOLAR N. 7 CCM1 MISSÃO EMANUEL</option>
<option>[EQT] COMPLEXO ESCOLAR N. 3 CCM1 MWENE TCHIMONGUA</option>
<option>[EQT] COLÉGIO N. 01 CCM1 COMANDANTE KUENHA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 8 CCM1 MWENE SALINDONGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 18 CCM1 MWENE LINGONGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 12 CCM1 MWENE VULOMBO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE MAVINGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 4 CCM1 MWENE KAPUSU</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 17 CCM1 MWENE TCHIKOLOLO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 10 CCM1 MWENE KALIATA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 328-PADRE LEONARDE</option>
