<option>[EQT] COLÉGIO N. 26 JÚLIO ALBERTO HENRIQES - TOMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 25 CAPALA - TOMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 24 MAMEDES - TOMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 9 - 17 JUNHO - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 18 - BUCO – ZAU - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 1 - NZINGA MBANDI - TÔMBWA</option>
<option>[EQT] COLÉGIO N. 19 - 23 DE ABRIL - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 16 - 8 DE DEZEMBRO - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 4 - REI MANDUME - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 15 - 8 DE SETEMBRO - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 23 - ROCHA MAGALHÃES - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 10 - COLÉGIO CONEGO ZAGALO - TÔMBWA</option>
<option>[EQT] LICEU N. 6 - DR. ANTÓNIO AGOSTINHO NETO - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 11 - 8 DE JANEIRO - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 12 - PINDA - PAIVA - TÔMBWA</option>
<option>[EQT] DIRECCÃO MUNICIPAL DA EDUCAÇÃO DO TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 2 - DR. ANTÓNIO AGOSTINHO NETO - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 3 - GENERAL SIMIONE MUKUNE- TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 7 - JOÃO FIRMINO TCHINANGA - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 5 - KUROCA - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 22 - 22 DE NOVEMBRO - TÔMBWA</option>
<option>[EQT] INSTITUTO POLITÉCNICO N.21 - JOSÉ FRANCISCO REPUBLICANO - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 14 - COMANDANTE KASSANJE - TÔMBWA</option>
<option>[EQT] COLÉGIO N. 13 - 28 DE AGOSTO - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 17 - 2 DE MARÇO - TÔMBWA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 20 - 2 DE ABRIL - TÔMBWA</option>
<option>[EQT] CÓLEGIO N. 8 - FIDEL CASTRO - TÔMBWA</option>
