<option>[EQT] ESCOLA PRIMÁRIA N. 133 DO KAWAZANGA Z - B</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 127 ALBERTO SAMÁRIO RECUA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 126 DOMINGAS MUTA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 125 JOSÉ CAMUAMBA MUACAHIADO B. ZAGE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 134 - BAPTISTA BUMBA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 132 - DO BAIRRO KAWAZANGA Z - D</option>
<option>[EQT] COMPLEXO ESCOLAR N. 131 - DO BAIRRO CANDEMBE Z - D</option>
<option>[EQT] COMPLEXO ESCOLAR N. 130 - MARIA DOS SANTOS DA COSTA AFRICANO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 129 - DO BAIRRO SOCIAL DA JUVENTUDE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 128 - DO NHAMA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 124 - KATETA SAMALESSO</option>
<option>[EQT] INSTITUTO POLITÉCNICO DE ADMINISTRAÇÃO E GESTÃO N. 07 TERRA NOVA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 8 DR. ANTÓNIO AGOSTINHO NETO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 117 DO BAIRRO CARTEIRA 1</option>
<option>[EQT] ESCOLAR PRIMÁRIA N. 135  SÃO JOSÉ</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 106 DO BAIRRO KANOQUENA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 105 DO BAIRRO TXIPAMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 22 DO BAIRRO TXAPOJI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 111 DO SOMBO SEDE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 97 DO BAIRRO NGANDO</option>
<option>[EQT] COMPLEXO ESCOLAR ESNSINO ESPECIAL N. 01</option>
<option>[EQT] COMPLEXO ESCOLAR N. 17- MISSÃO FEMININA</option>
<option>[EQT] LICEU N. 02 SÃO KIZITO - SAURIMO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 27 GENERAL TXIZAINGA</option>
<option>[EQT] ESCOLA PRIMARIA N. 26 DO BAIRRO CANDEMBE 1</option>
<option>[EQT] COMPLEXO ESCOLAR N. 11 ILDA CALUPETECA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 09 ANTÓNIO COIMBRA DA SILVA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 123 JOSÉ NGUAMBE DO BAIRRO ZORÓ</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 12 14 DE ABRIL DO MANAUTO 1</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 06 TXIZAINGA - 1</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 79 MAJOR KANDJENGO</option>
<option>[EQT] ESCOLAPRIMÁRIA N. 18 LUAVUR ZONA B</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 57 DO BAIRRO SAMULAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 126 DO BAIRRO CAZARI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 41 1 DE DEZEMBRO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 12 MWONO WAHA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 14 RUTH HADLY MISSÃO CAMUNDAMBALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 11 MARIA DE LURDES MUALUEZE</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE SAURIMO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 43 DO BAIRRO SACOMBE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 50 DO BAIRRO SAMBAU</option>
<option>[EQT] COMPLEXO ESCOLAR N. 13 DO SUEJA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 56 DO BAIRRO MUANGUIJI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 36 1 DE JUNHO MULOMBE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 04 JONATE MÁRIO PINTO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 2- PADRE HENRIQUE GROESMITH</option>
<option>[EQT] ESCOLAPRIMÁRIA N. 08 DO BAIRRO LUAVUR ZONA C</option>
<option>[EQT] COMPLEXO ESCOLAR N. 32 JOSÉ TXIESSUETXIPI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 70 DO BAIRRO SACAMBUNDJI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 62 DO BAIRRO CAICANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 92 DO BAIRRO TXANGUILO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 120 ALONE CHINEQUE</option>
<option>[EQT] INSTITUTO TÉCNICO DE SAÚDE N. 01 - SAURIMO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 15 -JOSÉ MARIA ROBLES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 20 DO BAIRRO CAMITUNDO</option>
<option>[EQT] COLÉGIO N. 01 MUATXISSENGUE WA - TEMBO</option>
<option>[EQT] COLÉGIO N. 04 "4 DE ABRIL "</option>
<option>[EQT] COLÉGIO N. 02 EX II NÍVEL</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 91 DO BAIRRO CALIWE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 05 JOSÉ MANUEL LUEMBE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 25 DO BAIRRO MUANDONJI - CAXITA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 17 PARÓQUIA SANTO ANTÓNIO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 23 DO BAIRRO CANDEMBE 2</option>
<option>[EQT] INSTITUTO POLITÉCNICO N. 08 LUAR - SAURIMO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 14 DO BAIRRO NGAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 71 DO BAIRRO CASSAMBA 2</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 77 DO BAIRRO SAQUEMBUE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 1 DR. RAÚL FERNANDES JUNIOR</option>
<option>[EQT] COMPLEXO ESCOLAR N. 13 DO MANAUTO 2</option>
<option>[EQT] COLÉGIO N. 07 CAMUNDAMBALA</option>
<option>[EQT] MAGISTÉRIO N. 01 AMOR DO POVO DE SAURIMO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 04 -17 DE SETEMBRO</option>
<option>[EQT] COLÉGIO N. 06 CANDEMBE II</option>
<option>[EQT] GABINETE PROVINCIAL DA EDUCAÇÃO DA LUNDA - SUL</option>
<option>[EQT] LICEU N. 01 JOSÉ MANUEL SALUCOMBO - SAURIMO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 65 DO BAIRRO LUHEMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 82 DO BAIRRO KAIAZA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 84 DO BAIRRO LNDJATE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 16 SÃO JOÃO CALÁBRIA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 101 DO BAIRRO PESO VELHO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 68 DO BAIRRO NANGUAZA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 35 DO BAIRRO MUANGUEJI</option>
<option>[EQT] INSTITUTO MÉDIO POLITÉCNICO DA LUNDA - SUL N. 01</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 58 DO BAIRRO MUATOYO - SACAXIMA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 06 MAHATMA GANDHI REGEDORIA CAZEMBE</option>
<option>[EQT] COLÉGIO N. 05 22 DE NOVEMBRO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 48 SAMUPAFO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 10 COMANDANTE TXIZAINGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 114 DO BAIRRO CATEWE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 33 BEATO CARLO STEEB</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 19 SANTA ANA ALDEIA DA MISSÃO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 21 DO BAIRRO PELENGUE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 09 28 DE AGOSTO TXICUMINA</option>
<option>[EQT] COLÉGIO N. 03 28 DE MAIO</option>
<option>[EQT] COMPLEXO ESCOLAR 1 DE JUNHO N. 98 DE MONA - QUIMBUNDO</option>
<option>[EQT] INSTITUTO AGRÁRIO MONA - QUIMBUNDO N. 9 - SAURIMO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 85 DO BAIRRO PIMBI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 44 DO BAIRRO ITENGO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 39 KAIMBO KAMBUANDJI SAMENECA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 24 DO BAIRRO LUAVUR ZONA A</option>
<option>[EQT] ESCOLA PRIMARIA N. 34 DO BAIRRO LUAR</option>
<option>[EQT] COMPLEXO ESCOLAR N. 40- PEDRO MANUEL</option>
