<option>[EQT] COMPLEXO ESCOLAR DR. A. NETO - CASSÚSSUA QUILENDA</option>
<option>[EQT] COMPLEXO ESCOLAR BURICA NHAMA - QUILENDA</option>
<option>[EQT] COMPLEXO ESCOLAR BANZA QUILENDA/JOSÉ EDUARDO DOS SANTOS</option>
<option>[EQT] ESCOLA PRIMÁRIA DO QUIMBAGE - QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA DA CALUCANDA - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DON JOÃO DE OLIVEIRA MATOS - QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA DO LUPEMBE - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA LUNDO DE CIMA - QUILENDA</option>
<option>[EQT] COMPLEXO ESCOLAR DR. A. NETO - QUIRIMBO - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA AUGUSTO NGANGULA - CAPILO - QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA LONGA - NHIA QUILENDA</option>
<option>[EQT] MAGISTERIO 17 DE SETEMBRO - QUILENDA</option>
<option>[EQT] COMPLEXO ESCOLAR 04 DE ABRIL QUISSENGUE - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA 332 - QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA BANZA SONGO - RIAMBIMBI - QUILENDA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DE EDUCAÇÃO DA QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA 10 DEZEMBRO MBANZA CASSÚSSUA - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA COMANDANTE BULA - MASSANGO - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DA CATAMBA DA XARIAIA - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA 22 DE NOVEMBRO MBALA - QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA DO MURIMBO - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO ANDULO AMBIR - QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA NGINGA MBANDY - CAGIR QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DA IPAPA - QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA BANZA MUHONGO - QUILENDA</option>
<option>[EQT] COMPLEXO ESCOLAR DEOLINDA RODRIGUES - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA KIALA SACA - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA COMANDANTE DANGEREUX - NGUNZA - QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA DA HUMBA - QUILENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA CANONGUENA - QUILENDA</option>
<option>[EQT] COLÉGIO 14 DE ABRIL - QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA NGOLA KILUANGE - HAMA QUILENDA</option>
<option>[EQT] ESCOLA PRIMARIA BANZA SACA - QUILENDA</option>
