<option>[EQT] ESCOLA PRIMÁRIA BG 8107 - SAIDY VIEIRA MINGAS - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8003 - CAILUNGA - CAIMBAMBO</option>
<option>[EQT] COLÉGIO BG 8099 - DR. ANTÓNIO AGOSTINHO NETO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8010 - KASSIMA VIVO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8071 - EYENDUE II - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8086 - CATUIO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8101 - BAMBI - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8104 - CDTE FERNANDO SEQUETA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8057 - ENGUENGUE - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8073 - 22 DE NOVEMBRO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8023 -14 DE ABRIL-MALOWA II-CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8024 - MATA-FOME - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8067 -HOJI-YA-HENDA-KOQUIMA-CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8055 CDTE KASSANJI - TCHIMBOTO -CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8053 - COMANDANTE BOAL - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8033 - CALONDEIA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8008 - CDTE VALÓDIA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8030 - CAINAMBA - CAIMBAMBO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8026 - UNDONGO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8048 - LUWE - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8076 - DEOLINDA RODRIGUES - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8084 - TCHIMBACA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8002 - KAISSACA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8079 - CATALA LONGONGO - CAIMBAMBO</option>
<option>[EQT] COLÉGIO BG 8103 - JOSÉ EDUARDO DOS SANTOS - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8034 - CALONDO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8025 - 28 DE AGOSTO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8062 - 1 DE JUNHO - SOLO -  CAIMBAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 8095 - NINGUININGUI - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8087 - TCHINHUÑGO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8075 - SIMAYOMBE - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8061 -  MAHUMBULO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8046 - EPUMO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8089 - CDTE KASSANJI - PATOS - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8007 - CDTE HOJI-YA-HENDA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8078 - 17 DE SETEMBRO - CALIMA -CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8096 - 14 DE ABRIL - UPUNGO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8088 - PE.DOMINGOS C. NUNDA-CAIMBAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 8098 - KAYAVE - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8082 - ETEPA - CAIMBAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 8097 - 4 DE FEVEREIRO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8064 - 4 DE ABRIL - EPUNDA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8093 - 11 DE NOV. - COPOROLO-CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8011 - KATALA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8070 - EYENDUE I - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8077 - MUNDOMBE - CAIMBAMBO</option>
<option>[EQT] LICEU BG 8100 - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8014 - REI MANDUME - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8016 - JANJALA I - CAIMBAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 8092 - CATENGUE - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8043 - CUAUNGA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8145 - JEREMIAS D.TCHILELEVICA -CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8047 - LOSSANJI - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8094 - 4 DE ABRIL - LIMBUATA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8009 - 17 DE SET. - PUPIRA -CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8018 - NGOLA KILUANJE - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8065 - EKUIKUI I - CAIMBAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 8091 - CANHAMELA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8044 - DIMBA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8050 - COPOROLO SERRAÇÃO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8056 - CAPONTE KEVAIA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8031 - CAISSISSI - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8102 - VENTOINHA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8049 - ALTO HALO - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8039 - TCHIMBANDI - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8022 - 11 DE NOV. - MALOWA- CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8083 - NGUNDJI - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8059 - EVUVI - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8068 - DEMBI - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8063 - BUMBUA - CAIMBAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 8042 - COTOLO - CAIMBAMBO</option>
