<option>[EQT] ESCOLA PRIMÁRIA BG 2110 - SÃO JOÃO BAPTISTA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2111 - ALTO ESPERANÇA 2 - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2109 - BOA VISTA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2107 - GUILHERME H. G. C. LIMA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA  BG 2112 - BOA VISTA BAIXA - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2103 - CENTRALIDADE - LOBITO</option>
<option>[EQT] INSTITUTO TÉCNICO DE SAÚDE BG 2102 - LOBITO</option>
<option>[EQT] MAGISTÉRIO BG 2088 - ICRA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2108 - DAMIÃO TOMÉ - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2101 - JOSÉ ILÍDIO CH. MANJENJE - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2064 - NGOLO D´AREIA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2063 - EKOLELO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2416 - CDTE KASSANJI - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2072 - EKUIKUI II - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2001 - 22 DE NOVEMBRO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2017 - PEDRO M. P. "KANOMBA" - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2051 - IMACULADO COR. DE MARIA - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2029 - HANHA DO NORTE - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2100 - EVANG. DA ZONA COMERCIAL - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2080 - MONTARROI DA CANJALA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2075 - 4 FEVEREIRO - CANJALA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2032 - BAIXO PUNDO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2085 - BULA MATADY - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2089 - 1º DE AGOSTO - LOBITO</option>
<option>[EQT] COLÉGIO BG 2000 - DOM ÓSCAR BRAGA - LOBITO</option>
<option>[EQT] LICEU BG 2061 - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2041 - 8 DE MARÇO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2046 - ALTO AKONGO - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2113 - CONVENÇÃO BAPTISTA - LOBITO </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2078 - DR. ANTÓNIO A.NETO-CANJALA- LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2020 - 4 DE ABRIL - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2039 - 25 DE FEVEREIRO-EGI. PRAIA- LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2044 - BOM SAMARITANO - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2012 - EVANGÉLICO DA CANATA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2106 - NICOLAU GOMES SPENCER - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2065 - NZINGA MBANDI - LOBITO</option>
<option>[EQT] COLÉGIO BG 2007 - HOJI-YA-HENDA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2025 - CDTE LIBATA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2105 - ALTO MBANGO MBANGO - LOBITO </option>
<option>[EQT] MAGISTÉRIO BG 2026 -  SANTA CRUZ - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2052 - MBANGO MBANGO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2014 - SÃO PEDRO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2021 - 1 DE JUNHO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2076 - 1 DE JUNHO DA CANJALA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2098 - SAGRADA VICTÓRIA - LOBITO</option>
<option>[EQT] INSTITUTO POLITÉCNICO BG 2027 - LOBITO  </option>
<option>[EQT] COMPLEXO ESCOLAR BG 2043 - SÃO JOÃO BAPTISTA - LOBITO</option>
<option>[EQT] COLÉGIO BG 2015 - REI MANDUME - LOBITO</option>
<option>[EQT] COLÉGIO BG 2022 - NOSSA SRA. DA SABEDORIA - LOBITO</option>
<option>[EQT] COLÉGIO BG 2087 - CDTE VALÓDIA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2090 - JARDIM ESCOLA - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2010 - SAGRADA ESPERANÇA - LOBITO</option>
<option>[EQT] MAGISTÉRIO BG 2050 - SANTA DOROTEIA - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2040 - M. KAVINDA - EGI. PRAIA - LOBITO </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2066 - AKONGO - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2054 - EVANGÉLICO DO GOLF - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2023 - EVANGÉLICO DO ALTO LIRO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2073 - CDTE GIKA - LOBITO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2260 - KARL MARX - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2006 - DEOLINDA RODRIGUES - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2028 - MARCELINO DIAS - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA  BG 2030 - CULANGO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2091 - AGOSTINHO EPALANGA - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2104 - DR.JOAQUIM DOM. PINHEIRO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2037 - 10 DE DEZEMBRO - CANJALA - LOBITO</option>
<option>[EQT] COLÉGIO BG 2034 - 11 DE NOVEMBRO - CANJALA - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2008 - EVANGÉLICO DA GALILEIA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2081 - DESPERTAR DO EGIPTO PARIA- LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2077 - CAÊNDA DA CANJALA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2053 - KAJENDENDE - LOBITO</option>
<option>[EQT] COLÉGIO BG 2019 - MISSIONÁRIO DE SÃO PAULO - LOBITO  </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2009 - 27 DE MARÇO - LOBITO</option>
<option>[EQT] COLÉGIO  BG 2024 - JOSÉ SAMUEL - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2236 - DANGERUX - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2083 - REVOLUÇÃO DE OUTUBRO - LOBITO</option>
<option>[EQT] COLÉGIO BG 2099 - EMANUEL - LOBITO</option>
<option>[EQT] COLÉGIO BG 2031 - CULANGO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2003 - 16 DE JUNHO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2069 - 4 DE JANEIRO - CANJALA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2002 - ALTO ESPERANÇA - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2071 - EBENEZER - LOBITO</option>
<option>[EQT] INSTITUTO POLITÉCNICO BG 2047 - PE. MARTINS FERREIRA- LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2018 - 17 DE SETEMBRO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2004 - REI MANDUME - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2186 - DR. ANTÓNIO AGOSTINHO NETO- LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2005 - 4 DE FEVEREIRO - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2305 - ANGOLA LIBERTADA - LOBITO</option>
<option>[EQT] COLÉGIO BG 2042 - HERÓIS DE KANGAMBA - LOBITO</option>
<option>[EQT] MAGISTÉRIO BG 2013 - CDTE KWENHA - LOBITO </option>
<option>[EQT] COLÉGIO BG 2011 - MAJOR SAIDY VIEIRA DIAS MINGAS - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2035 - ROSSELA RINALDI - CANJALA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2209 - MUTU-YA-KEVELA - LOBITO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 2016 - CALEIRA 27 DE MARÇO - LOBITO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 2045 - REI KATYAVALA - LOBITO</option>
