<option>[EQT] COLEGIO N. 08 CCC1 – COMANDANTE KUENHA</option>
<option>[EQT] COLEGIO N. 17 CCC1 – VANDA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CALAI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 02 - CCC1 - 22 DE NOVEMBRO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 19 - CCC1 - NDAMU - NDAMU</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 07 - CCC1 - KAMPANZA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 10 - CCC1 - 11 DE NOVEMBRO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 06 - CCC1 - NANGURA ZA SIYAKA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 01 - CCC1 - COMANDANTE DANGEUREX</option>
<option>[EQT] LICEU N. 16 - CCC1 - 22 DO CALAI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 09 - CCC1 - 17 DE SETEMBRO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 04 - CCC1 - KAFULO</option>
