<option>[EQT] ESCOLA PRIMÁRIA DE OHAKAONDE II - NAMACUNDE</option>
<option>[EQT] COLÉGIO REI MANDUME-YA-NDEMUFAYO - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHANA-SHA-NANDJILI - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMATEMBA - NAMACUNDE</option>
<option>[EQT] COLÉGIO 22 DE NOVEMBRO DO CHIEDI - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAYOLWA - NAMACUNDE</option>
<option>[EQT] COMPLEXO ESCOLAR DE OMULOVA - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA 17 DE SETEMBRO DE EHENGE - NAMACUNDE</option>
<option>[EQT] COMPLEXO ESCOLAR DE OMULUNGA-WA-SHIKONGO - NAMACUNDE</option>
<option>[EQT] MAGISTÉRIO DE NAMACUNDE</option>
<option>[EQT] ESCOLA PIMÁRIA DE OKWADJOMUDI - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMANDOBE - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA 4 DE ABRIL DA SANTA CLARA - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMWANDI - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKADWEYA - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ENYOMBUI - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OHEYOKA - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OYONGO - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SHIEDI-SEDE - NAMACUNDE</option>
<option>[EQT] COMPLEXO ESCOLAR DE OWANGWE - NAMACUNDE</option>
<option>[EQT] COMPLEXO ESCOLAR DE ONGWE - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ENOLEU - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OIKUNDU - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMULEMBA - NAMACUNDE</option>
<option>[EQT] COMPLEXO ESCOLAR NDJUKUMA-YA-SILENGIFA -NAMACUNDE</option>
<option>[EQT] COMPLEXO ESCOLAR DE OKAWE KM12 - NAMACUNDE</option>
<option>[EQT] COMPLEXO ESCOLAR DE OIHOLE - NAMACUNDE</option>
<option>[EQT] COMPLEXO ESCOLAR DE OFENDA - NAMACUNDE</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO NAMACUNDE</option>
<option>[EQT] COMPLEXO ESCOLAR DE OUNONGE MARCO 16 - NAMACUNDE</option>
<option>[EQT] COLÉGIO DE SANTA CLARA - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA 1 DE JUNHO DE NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONAMWENYO - NAMACUNDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMUKWA-WA-SHINDJALA - NAMACUNDE</option>
