<option>[EQT] COLÉGIO BG 0046 - CABAIA - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0040 - EBENEZER ICEA- CATUMBELA</option>
<option>[EQT] MAGISTÉRIO BG 0038 - 5 DE OUTUBRO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0039 - 4 DE ABRIL - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0036 - SANTO ISIDRO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0019 - 4 DE FEVEREIRO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0044 - CENTRALIDADE DO LUONGO - CATUMBELA</option>
<option>[EQT] INSTITUTO POLITÉCNICO BG 0031 -  ADMINIST GESTÃO - CATUMBELA</option>
<option>[EQT] COLÉGIO BG 0037 - LÚCIO LARA - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0002 - AUGUSTO NGANGULA - CATUMBELA</option>
<option>[EQT] COLÉGIO BG 0014 MARC - LUONGO - CATUMBELA</option>
<option>[EQT] COLÉGIO BG 0007 - CDTE DANGEREUX - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0025 - SÚPUA ESQUERDA - CATUMBELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 0024 - GAMA - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0009 - HÉLDER NETO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0003 - CDTE KASSANJI - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0010 - IRENE KOHEN - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0006 - DEOLINDA RODRIGUES - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0000 - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0035 - SÓCRATES DÁSCALO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0027 - CDTE VALÓDIA - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0034 - NOVA ESPERANÇA - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0029 - NGOLA KILUANJI - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0022 - POVO UNIDO - CATUMBELA</option>
<option>[EQT] COLÉGIO BG 0032 - 4 DE JANEIRO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0012 - LUCRÉCIA PAIM - CATUMBELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 0020 - 11 DE NOVEMBRO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0041 - 11 DE MARÇO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0017 - 1º DE JUNHO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0004 - CDTE GIKA - CATUMBELA</option>
<option>[EQT] COLÉGIO BG 0018 - 5 DE JUNHO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0021 - SIMIONE MUCUNE - CATUMBELA</option>
<option>[EQT] COLÉGIO BG 0016 - RAÚL DAVID - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0033 - REGEDOR ALFREDO - CATUMBELA</option>
<option>[EQT] LICEU BG 0043 - CHEC - CATUMBELA</option>
<option>[EQT] LICEU BG 0026 - PE. EMIL FRIK - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0008 - FERRAZ BOMBOCO - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0001 - AMÉRICO BOAVIDA - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0015 - RAINHA DA PAZ - CATUMBELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 0045 - CENTRALIDADE - LUONGO - CATUMBELA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DA CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0023 - PATRICE LUMUMBA - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0013 - MUTU-YA-KEVELA - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0005 - CABAIA - CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 0047 - CATUMBELA</option>
