<option>[EQT] COLÉGIO Nº 87 CDTE HOJE-YA-HENDA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 36 CAPETI LONDUIMBALI</option>
<option>[EQT] COLÉGIO Nº88 VILA FRANCA DO KEVE LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 66 CHALIWEWA LONDUIMBALI</option>
<option>[EQT] COLÉGIO Nº 86 VIRGÍLIO DE TODOS SANTOS LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 53 DO ALTO-HAMA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº13 DE JUNJULO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 47  VILA HOMBO - LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 79 REI MANDUME - EPAMA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 69 LUVILI LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 56 CHICALA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 43 - NUÑGULO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 42 - MACA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 29 CHISSONDE LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 26 MAYELA NGUMBE LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 24 ALBERTO MIAPIA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 1 COMANDANTE FEIJÓ LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 9 CUNJUCA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 61 CASSOPOLA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 54 MISSÃO LONDUIMBALI</option>
<option>[EQT] COLÉGIO ALBANO MACHADO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 40 - PUCUSSO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 23 ESSANGO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 14 ENSINO DE ADULTOS LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 31 CHIQUEME DE CUMBILA - LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 55 CASSÓLEO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 33 CHIMBUNGUE LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 25 CHAWAYALA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 57 CHISSEIA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 6 COMANDANTE BANDEIRA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 41 SAMUNGUVA LONDUIMBALI</option>
<option>[EQT] LICEU 11 DE NOVEMBRO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 78 OMBALA MIGUEL LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 58 ESSOQUELA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 39 - BEU LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 16 HONDOQUELA LONDUIMBALI</option>
<option>[EQT] COLÉGIO COMANDANTE FEIJÓ LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 60 BONGA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 3 CDTE FEIJÓ LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 70 LOSSANGO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 34  - LONDUIMBALI</option>
<option>[EQT] LICEU OTCHIVANDA - LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 74 CANGOLO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 21 SASSOMA LONDUIMBALI</option>
<option>[EQT] COLÉGIO Nº89 COMANDANTE VALÓDIA  LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 8 CUQUETA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 7 CHITACA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 50 - CALONGUNDA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 11 SAMANJAMBA LONDUIMBALI</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DE LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 76 CAMBAMBI LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 67 GUNGO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 64 BABAERA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 63 C. HUMBI LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 5 COMANDANTE DANGEREUX LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 47 - V. HOMBO LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 46 - VILA FRANCA LONDUIMBALI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 4 CAMUPA LONDUIMBALI</option>
<option>[EQT] COLÉGIO Nº90 CDATE LÚCIO LARA DA GALANGA - LONDUIMBALI</option>
<option>[EQT] ESCOLA DE MAGISTÉRIO  - ADPP LONDUIMBALI</option>
