<option>[EQT] ESCOLA PRIMÁRIA BG 3008 - 4 DE ABRIL - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3383 - BAÍA - FARTA</option>
<option>[EQT] COLÉGIO BG 3029 - COMANADANTE DANGREUREX - BAÍA-FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3014 -  MUHANINGO - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3028 - FORNO - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3012 - CHIOME - BAÍA - FARTA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 3053 - S. FRANCISCO XAVIER - BAÍA-FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3018 - 14 DE ABRIL - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3025 - HENGUE - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3052 - SALINA - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3043 - BANDEIRA - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3041 - ACINDE - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3002 - ANTÓNIO C. BETTENCOURT- BAÍA-FARTA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 3010 - CHAMUME - BAÍA-FARTA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 3057 - URBANIZAÇÃO PIMA - BAÍA - FARTA </option>
<option>[EQT] INSTITUTO POLITÉCNICO BG 3050 - BAÍA-FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3026 - BOA ESPERANÇA - BAÍA - FARTA </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3021 - BOA LEMBRANÇA - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3047 - POVO UNIDO - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3023 - NDOLOMA - BAÍA - FARTA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DA BAÍA-FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3009 - 22 DE NOVEMBRO - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3006 - 11 DE NOVEMBRO - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3032 - CHICUHUM - BAÍA - FARTA</option>
<option>[EQT] COLÉGIO BG 3046 - SAPANGUELE - BAÍA - FARTA  </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3004 - ALTO LIRO - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3007 - COMANTE KASSANJI -A - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3019 - COMANDANTE KASSANJI - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3033 - 4 DE FEVEREIRO - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3049 - 16 DE JUNHO - BAÍA - FARTA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 3031 - KALOHANGA - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3040 - CANTO - BAÍA - FARTA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 3015 - MUTU-YA-KEVELA - BAÍA-FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3024 - DR. ANTÓNIO A. NETO- BAÍA - FARTA </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3048 - MISSIONÁRIA DE CANAÃ- BAÍA - FARTA</option>
<option>[EQT] MAGISTÉRIO BG 3016 - SANTA ANA - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMARIA BG 3020 - JOSÉ MARTY DA BAIA-FARTA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 3005 - KASSANJI B - BAÍA-FARTA</option>
<option>[EQT] COLÉGIO BG 3001 - 1º AGOSTO - BAÍA-FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3003 - 10 DE DEZEMBRO - BAÍA - FARTA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 3056 - URBANIZAÇÃO PIMA - BAÍA - FARTA</option>
<option>[EQT] ESCOLA TÉCNICA DAS PESCAS - BG 3051 - BAÍA-FARTA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 3013 - SACO - BAÍA - FARTA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 3039 - JUJÚ DA COSTA VALÉRIO- BAÍA-FARTA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 3000 - COMANDANTE COW-BOY - BAÍA-FARTA</option>
