<option>[EQT] COLÉGIO N. 52 SEDE DO ANDULO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE KATALA E CHIMBAMBA/CHUVAULO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE DENGUE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIPEIO, UTALAMO E SIMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SAMEIRO</option>
<option>[EQT] ESCOLA PRIMÁRIO DE NGOLA CALINDA S. PAULO,SAMARIA CASSISSA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHISSAQUE MUENGA E NJILINGA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CASSUAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHOMBA /BOA ESPERANÇA</option>
<option>[EQT] COMPLEXO ESCOLAR DO 7º DIA CHICUMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ETALELA E CHIMBINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA CHIVAÚLO/SEDE, CANANA, CHIÚLA E DONDEIRO</option>
<option>[EQT] ESCOLA PRIMARIA DE SEABRA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CARIWEQUE SACHIPIA E CAMBANGO</option>
<option>[EQT] ESCOLA PRIMARIA DE CHICALA GALILEIA E CHICALA PINTO</option>
<option>[EQT] COMPLEXO ESCOLAR DR. ANTÓNIO A. NETO - ANDULO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CATALA LONDUIBALI E VISSAMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE PILOTO/CALUSSINGA</option>
<option>[EQT] ESCOLA PRIMARIA DE CAMBUANDA-ANDULO</option>
<option>[EQT] ESCOLAS PRIMARIA DE CALIFONGO E CATASSI</option>
<option>[EQT] COLÉGIO 11 DE NOVEMBRO DE CHIVAÚLO</option>
<option>[EQT] ESCOLA PRIMARIA DE ETANDA E CASSOMA</option>
<option>[EQT] ESCOLA PRIMARIA DE SICATO E CACOMBO</option>
<option>[EQT] ESCOLA PRIMARIA DE BOA VISTA-ANDULO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BELO - MONTE E EYELA</option>
<option>[EQT] COMPLEXO ESCOLAR DE CHILESSO-CHIVAULO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMUNDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE HOJI - YA - HENDA/ CALUSSINGA</option>
<option>[EQT] ESCOLA PRIMARIA DE CANATA CHINDUNDULA DENGUE E TRIUMFO</option>
<option>[EQT] ESCOLAS PRIMARIA DE CHIPEMBE/ NÁZARA-CASSUMBI</option>
<option>[EQT] ESCOLA PRIMARIA 42- SEDE ANDULO</option>
<option>[EQT] ESCOLA PRIMARIA DA TACA UNDO E SAMOMA</option>
<option>[EQT] COMPLEXO ESCOLAR DE BUANGA E ESSANJO</option>
<option>[EQT] COMPLEXO ESCOLAR MIS. ADVENTISTA DO 7º DIA -ANDULO</option>
<option>[EQT] LICEU 4 DE FEVEREIRO - ANDULO</option>
<option>[EQT] ESCOLA PRIMARIA DECHIMOÑA LUONGO TCHISSEYA E B.V ECOSSA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LOBITO MUEMBESSI E ETAMBA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO ANDULO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIMBUIO E CASSUAMA </option>
<option>[EQT] ESCOLA PRIMÁRIA DE ULIMBA ICUALU, ECOVONGO E KASIKA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CACHITUNGO E CHINGUENDA</option>
<option>[EQT] ESCOLA PRIMARIA 4 DE ABRIL CHIVILI1</option>
<option>[EQT] ESCOLA P. ASSEMBLEIA DE DEUS PENTECOSTAL E CHALIWEWA</option>
<option>[EQT] COLEGIO 11 DE NOVEMBRO- SEDE ANDULO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NGANGO E CHIUCO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHILONDA/KAKUVA E EPANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHILENGUE E CHINDUNDUMA E JERUSALEM</option>
<option>[EQT] ESCOLA PRIMARIA DE TECNIL-SEDE</option>
<option>[EQT] COMPLEXO ESCOLAR DE CHIOMBO</option>
<option>[EQT] ESCOLAS PRIMARIA DE CATAPI E ETUMBULUCO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE KANDELE, CATUMBA, SAVANGA E TIMOR</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NHONGO CHICUMA E CANDUMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MUANDI CHINDONGA E CANTINA</option>
<option>[EQT] ESCOLA PRIMARIA DE LUNGUNDUA</option>
<option>[EQT] ESCOLA PRIMARIA DE LUCUCO E ETUNDA CHIVANGUE</option>
<option>[EQT] COMPLEXO ESCOLAR  DE CAYUVA</option>
<option>[EQT] ESCOLAS PRIMARIA DE CHOMBA-ANDULO</option>
<option>[EQT] COMPLEXO ESCOLAR DE CANDUVENE E CHIWILA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIVENGUELA E VILA ESTRELA</option>
<option>[EQT] COMPLEXO ESCOLAR DEOLINDA RODRIGUÊS N. 80 - SEDE ANDULO</option>
<option>[EQT] ESCOLAS PRIMARIA DE CHIMBAMBA/CASSUMBI</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TUMBA, NÁZARA E SODOMA</option>
<option>[EQT] ESCOLA PRIMARIA DE SAMBALANDA CASSANDA E  EYOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE Bº HOSPITAL E MAPTESS</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NHEMBA</option>
<option>[EQT] COLÉGIO DA SEDE DE CHIVAULO</option>
<option>[EQT] COLEGIO SOMA NDOMBE</option>
<option>[EQT] COLÉGIO CHIPOLOCOSSO-ANDULO</option>
<option>[EQT] COMPLEXO ESCOLAR DE CARIONGO E LOVINGE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NDULO - EPALANGA E BELEM</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BUNJA CATASSI E HOMBO</option>
<option>[EQT] INSTITUTO TECNICO AGRARIO DO ANDULO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ESSULAMBANDA E KAHATANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE DONDEIRO ALTO E BAIRRO SILVA</option>
<option>[EQT] ESCOLA PRIMÁ. N. 414 CHISSEQUE</option>
<option>[EQT] COMPLEXO ESCOLAR DE CANGALO BANDO TALAVENDO E CAWAVA</option>
<option>[EQT] ESCOLA PRIMÁRIA TECNIL/CALUSSINA E CALENGA</option>
<option>[EQT] ESCOLAS PRIMARIA DE CANGONGO E CHITALINGA</option>
<option>[EQT] COMPLEXO ESCOLAR DE CANANA-ANDULO</option>
<option>[EQT] ESCOLA PRIMARIA DE CACHITELE E CAVAMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NGUMBA SAMUCUAYA E GARI</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SÃO PAULO</option>
<option>[EQT] COLÉGIO 8 DE MARÇO-CALUSSINGA</option>
<option>[EQT] MAGISTÉRIO SIMIONE MUCUNE - ANDULO</option>
<option>[EQT] ESCOLAS PRIMARIA DE ELIENGUE E CANANA-CASSUMBI</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIVINGA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE POVOAÇÃO DE CHICUMBI E BETATELA</option>
<option>[EQT] COMPLEXO ESCOLAR DE TUNDA CHISSOCOCUA ENHUANGULI E T CAPEIO</option>
<option>[EQT] ESCOLAS PRIMARIA DE LUVALO E NGONGO - MISSUNGA</option>
<option>[EQT] ESCOLAS PRIMARIA DE CASSUMBI-SEDE</option>
<option>[EQT] ESCOLA PRIMARIA DE SAUMERO-ANDULO</option>
<option>[EQT] ESCOLA PRIMÁRIA DEOLINDA RODRIGUES/CALUSSINGA E CATELE</option>
<option>[EQT] COMPLEXO ESCOLA NOSSA SENHORA DAS GRAÇAS</option>
<option>[EQT] ESCOLA PRIMARIA DE SENJE1 MANDE E VAVAYELA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NHANI-ANDULO</option>
