<option>[EQT] COMPLEXO ESCOLAR N. 1015-CAMBONDO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 1017-CALEBA </option>
<option>[EQT] ESCOLAR DO ENSINO PRIMÁRIO N. 1008 B - BETA</option>
<option>[EQT] ESCOLA PRIMÁRIA N.1010-CACANGA </option>
<option>[EQT] ESCOLA PRIMÁRIA N.1009-MISSIONÁRIA SANTO HILARIÃO </option>
<option>[EQT] COMPLEXO ESCOLAR Nº 1016-CÊRCA</option>
<option>[EQT] ESCOLA PRIMÁRIA N.1011-MALESSO </option>
<option>[EQT] COMPLEXO ESCOLAR N.1013-KILOMBO - KYA - PUTO</option>
<option>[EQT] COLÉGIO N. 1002- PATRICE EMERY LUMUMBA </option>
<option>[EQT] ESCOLA PRIMÁRIA N.1014-SANTA MARIA </option>
<option>[EQT] COLÉGIO N. 1003-CÔNEGO MANUEL DAS NEVES </option>
<option>[EQT] COMPLEXO ESCOLAR N.1012-CABINDA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇAO GOLUNGO ALTO</option>
<option>[EQT] LICEU N. 1001-GOLUNGO ALTO </option>
<option>[EQT] ESCOLAR DO ENSINO PRIMÁRIO N. 1007 A - BETA</option>
<option>[EQT] ESCOLA PRIMÁRIAN. 1005-QUIAPOSSE </option>
<option>[EQT] COMPLEXO ESCOLAR N. 1018-ANTÓNIO JACINTO DO AMARAL MARTINS</option>
<option>[EQT] COMPLEXO ESCOLAR N. 1006 CACOLOMBOLO</option>
