<option>[EQT] ESCOLA PRIMÁRIA N. 110 - ARNALDO PINTO GONÇALVES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 108 - JOÃO PEDRO CATUMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 109 - MANUEL FRANCISCO CASSUELE</option>
<option>[EQT] COLÉGIO N. 77 - ANTÓNIO LOPES DA CAMARA - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 06 - PRAIA AMÉLIA - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR 28 - CAMPO LIVRE - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 07 - 22 DE NOVEMBRO - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 75 - ANTÓNIO DA CONCEIÇÃO ANANAIS - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 36 - KAMBONGUE - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 82 - ANTÓNIO CONGO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 103 - BOM JESUS - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 03 - 4 DE FEVEREIRO - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 88 - SÃO JOÃO PAULO II - MOÇÂMEDES</option>
<option>[EQT] COLÉGIO N. 20 - 1 DE JUNHO- MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 25 - MACALA TCHIPATI - MOÇÂMEDES</option>
<option>[EQT] LAR DOS ESTUDANTES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 30 - 4 DE ABRIL - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 81 - DOM. MATEUS FELICIANO TOMÁS - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 13 - SÃO JOÃO BAPTISTA - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 79 - DOMINGOS CAPEWA - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 102 - RUI LUÍS FALCÃO PINTO DE ANDRADE - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 10 - TORRE DO TÔMBO - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 32 - SANTA TERESINHA MENINO DE JESUS - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 66 - EGÍDIO MARTINS TORRES - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 107 - JOSÉ BUNY - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 101 - ÁLVARO MANUEL DE BOA VIDA NETO - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 04 - 4 DE AGOSTO - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 67 - ANTÓNIO MAVELA - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 45 - CARUJAMBA - LUCIRA- MOÇÂMEDES</option>
<option>[EQT] INSTITUTO POLITÉCNICO Nº 55M PASCOAL LUVUALU - NAMIBE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 26 - ILHA DO MUNGONGO - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 12 - 5 DE ABRIL - MOÇÂMEDES</option>
<option>[EQT] LICEU N. 71 - 14 DE ABRIL - LUCIRA - MOÇÂMEDES</option>
<option>[EQT] INSTITUTO POLITÉCNICO DE ADMINISTRAÇÃO E GESTÃO DO NAMIBE N. 56 - ANTÓNIO JACINTO</option>
<option>[EQT] COLÉGIO N. 68 - COMANDANTE DANGEREUX - MOÇÂMDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 5- AUGUSTO NGANGULA- MOÇÂMEDES</option>
<option>[EQT] LICEU Nº 96 - SÃO TOMÁS DE AQUINO - NAMIBE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 11 - SÃO JOSÉ OPERÁRIO - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 29 - 50 SACO - MAR - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 74 - JOÃO INANA - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 15 - JOHN WESLEY - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 63 - EMÍLIO NGONGO - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 21 - TCHINDUCUTO - MOÇÂMEDES</option>
<option>[EQT] INSTITUTO TÉCNICO DE SAÚDE N. 97- MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 08 - NOVA PLATÓ - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 62 - REVERENDO EDUARDO MOREIRA KUENHE - MOÇÂMEDES</option>
<option>[EQT] MAGISTÉRIO N. 78 - JÚLIA LOPES - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 37 ANEXA - MOÇAMEDES</option>
<option>[EQT] COLÉGIO N. 38 - SÃO JOÃO PAULO II - MOÇÂMEDES</option>
<option>[EQT] LICEU N. 80 - AFONSO D. PEDRO VANDÚNEM MBINDA - MOÇÂMEDES</option>
<option>[EQT] COLÉGIO N. 48 - 11 DE NOVEMBRO - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 19 - MUTU-YA-KEVELA - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 64 - EMÍLIA DE ALMEIDA - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 23 - DR. ANTÓNIO AGOSTINHO NETO - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 60 - BOM DEUS - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 91- CDTE ANTÓNIO VICTOR TEIXEIRA DA CUNHA</option>
<option>[EQT] COLÉGIO N. 49 - SAIDY MINGAS - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 17 - PIONEIRO ZECA - MOÇÂMEDES</option>
<option>[EQT] COLÉGIO N. 52 - MARIA DE LOURDES VAN-DUNEM - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 42 - TOMÉ - BENTIABA- MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 18 - 31 DE JANEIRO - MOÇÂMEDES</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE MOÇÂMEDES</option>
<option>[EQT] LICEU N. 58M - WELWITSCHIA MIRABILIS - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 27 - 4 DE MARÇO - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 73 - ELLEN WHITE - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 33 - 4 DE JANEIRO - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 09 - RAINHA ZINGA MBANDI - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 39 - MACALA 70 - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 14 - KUSSY 2 - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 34 - 8 DE MARÇO - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 02 - HOJI-YA-HENDA - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 46 - SALOMÉ INÁCIO - LUCIRA- MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 72 - JOSÉ DA HORTA - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 24 - KUMANGALA - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 95 - REV. JAMES RUSSEL MCBETH - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 92 - AMÉLIA SIMÕES ALVES PATROCÍNIO - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 01 16 DE JUNHO - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 106 - BAIA DAS PIPAS - MOÇÂMEDES</option>
<option>[EQT] GABINETE PROVINCIAL DA EDUCAÇÃO DO NAMIBE</option>
<option>[EQT] COLÉGIO N. 50 - GABREIL KWANHAMA- MOÇÂMEDES</option>
<option>[EQT] MAGISTÉRIO N. 57 - PATRICE LUMUMBA - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 40 - ENSINO ESPECIAL - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 59 - MOSSAMBE - MOÇÂMEDES</option>
<option>[EQT] LICEU N. 69 - 10 DE DEZEMBRO - MOÇÂMEDES</option>
<option>[EQT] COLÉGIO N. 51 - 1 DE MAIO - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOKLAR N. 61 - RUY DUARTE DE CARVALHO - MOÇÂMEDES</option>
<option>[EQT] COLÉGIO N. 53 - REI MANDUME - MOÇÂMEDES</option>
<option>[EQT] MAGISTÉRIO N. 65 - ICRA - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 43 - SALINAS - BENTIABA- MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 44 - CENTRO BENTIABA - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 16 - DEOLINDA RODRIGUES - MOÇÂMEDES</option>
<option>[EQT] INSTITUTO POLITÉCNICO MARÍTIMO E PESQUEIRA N. 54 HÉLDER NETO - MOÇÂMEDES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 76 - JOSÉ ESTEVÃO - MOÇÂMEDES</option>
<option>[EQT] COLÉGIO N. 47 - EKUIKUI II - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 22 - NOSSA SENHORA DE FÁTIMA - MOÇÂMEDES</option>
<option>[EQT] COMPLEXO ESCOLAR N. 84 - JACOB KAVITA EVAMBE - IECA II - MOÇÂMEDES</option>
