<div class="mb-3">
    <select name="nome_centro" class="form-control multiplo" id="">
        @isset($centros)
            <option>{{ $centros->nome_centro }}</option>
        @else
            <option disabled selected>Selecione o centro</option>
        @endisset

        @if (Auth::user()->provincia == 'Bengo')

            @if (Auth::user()->municipio == 'Dande')
                @include('extra.centro.Bengo.Dande.index')
            @elseif (Auth::user()->municipio == 'Bula Atumba')
                @include('extra.centro.Bengo.Bula_atumba.index')
            @elseif (Auth::user()->municipio == 'Ambriz')
                @include('extra.centro.Bengo.Ambriz.index')
            @elseif (Auth::user()->municipio == 'Pango Aluqém')
                @include('extra.centro.Bengo.pango_aluquem.index')
            @elseif (Auth::user()->municipio == 'Dembos')
                @include('extra.centro.Bengo.Dembos.index')
            @elseif (Auth::user()->municipio == 'Nambuangongo')
                @include('extra.centro.Bengo.nambuangongo.index')
            @elseif (Auth::user()->municipio == 'Gombe')
                @include('extra.centro.Bengo.Gombe.index')
            @endif
        @elseif(Auth::user()->provincia == 'Benguela')
            @if (Auth::user()->municipio == 'Lobito')
                @include('extra.centro.Benguela.Lobito.index')
            @elseif (Auth::user()->municipio == 'Bocoio')
                @include('extra.centro.Benguela.Bocoio.index')
            @elseif (Auth::user()->municipio == 'Balombo')
                @include('extra.centro.Benguela.Balombo.index')
            @elseif (Auth::user()->municipio == 'Ganda')
                @include('extra.centro.Benguela.Ganda.index')
            @elseif (Auth::user()->municipio == 'Cubal')
                @include('extra.centro.Benguela.Cubal.index')
            @elseif (Auth::user()->municipio == 'Caiambambo')
                @include('extra.centro.Benguela.Caimbambo.index')
            @elseif (Auth::user()->municipio == 'Benguela')
                @include('extra.centro.Benguela.Benguela.index')
            @elseif (Auth::user()->municipio == 'Baía Farta')
                @include('extra.centro.Benguela.Baia_farta.index')
            @elseif (Auth::user()->municipio == 'Chongoroi')
                @include('extra.centro.Benguela.Chongoroi.index')
            @elseif (Auth::user()->municipio == 'Catumbela')
                @include('extra.centro.Benguela.Catumbela.index')
            @endif
        @elseif(Auth::user()->provincia == 'Bie')
            @if (Auth::user()->municipio == 'Cuito')
                @include('extra.centro.Bie.Cuito.index')
            @elseif (Auth::user()->municipio == 'Andulo')
                @include('extra.centro.Bie.Andulo.index')
            @elseif (Auth::user()->municipio == 'Nharêa')
                @include('extra.centro.Bie.Nharea.index')
            @elseif (Auth::user()->municipio == 'Cuemba')
                @include('extra.centro.Bie.Cuemba.index')
            @elseif (Auth::user()->municipio == 'Cunhinga')
                @include('extra.centro.Bie.Cunhinga.index')
            @elseif (Auth::user()->municipio == 'Catabola')
                @include('extra.centro.Benguela.Catabola.index')
            @elseif (Auth::user()->municipio == 'Camacupa')
                @include('extra.centro.Benguela.Benguela.index')
            @elseif (Auth::user()->municipio == 'Chinguar')
                @include('extra.centro.Bie.Chinguar.index')
            @elseif (Auth::user()->municipio == 'Chitembo')
                @include('extra.centro.Bie.Chitembo.index')
            @endif
        @elseif(Auth::user()->provincia == 'Cabinda')
            @if (Auth::user()->municipio == 'Cabinda')
                @include('extra.centro.Cabinda.Cabinda.index')
            @elseif (Auth::user()->municipio == 'Cacongo')
                @include('extra.centro.Cabinda.Cacongo.index')
            @elseif (Auth::user()->municipio == 'Buco-Zau')
                @include('extra.centro.Cabinda.Buco_zau.index')
            @elseif (Auth::user()->municipio == 'Belize')
                @include('extra.centro.Cabinda.Belize.index')
            @endif
        @elseif(Auth::user()->provincia == 'Cuando Cubango')
            @if (Auth::user()->municipio == 'Menongue')
                @include('extra.centro.Cuando_Cubango.Menongue.index')
            @elseif (Auth::user()->municipio == 'Cuito Cuanavale')
                @include('extra.centro.Cuando_Cubango.Cuito_cuanavale.index')
            @elseif (Auth::user()->municipio == 'Cuchi')
                @include('extra.centro.Cuando_Cubango.Cuchi.index')
            @elseif (Auth::user()->municipio == 'Cuangar')
                @include('extra.centro.Cuando_Cubango.Cuangar.index')
            @elseif(Auth::user()->municipio == 'Mavinga')
                @include('extra.centro.Cuando_Cubango.Mavinga.index')
            @elseif (Auth::user()->municipio == 'Calai')
                @include('extra.centro.Cuando_Cubango.Calai.index')
            @elseif (Auth::user()->municipio == 'Dirico')
                @include('extra.centro.Cuando_Cubango.Dirico.index')
            @elseif (Auth::user()->municipio == 'Rivungo')
                @include('extra.centro.Cuando_Cubango.Rivungo.index')
            @elseif (Auth::user()->municipio == 'Nancova')
                @include('extra.centro.Cuando_Cubango.Nancova.index')
            @endif
        @elseif(Auth::user()->provincia == 'Cuanza Norte')
            @if (Auth::user()->municipio == 'Cazengo')
                @include('extra.centro.Cuanza_norte.Cazengo.index')
            @elseif (Auth::user()->municipio == 'Lucala')
                @include('extra.centro.Cuanza_norte.Lucala.index')
            @elseif (Auth::user()->municipio == 'Ambaca')
                @include('extra.centro.Cuanza_norte.Ambaca.index')
            @elseif (Auth::user()->municipio == 'Golungo Alto')
                @include('extra.centro.Cuanza_norte.Golungo_alto.index')
            @elseif(Auth::user()->municipio == 'Cambambe')
                @include('extra.centro.Cuanza_norte.Cambambe.index')
            @elseif (Auth::user()->municipio == 'Quiculungo')
                @include('extra.centro.Cuanza_norte.Quiculungo.index')
            @elseif (Auth::user()->municipio == 'Bolongongo')
                @include('extra.centro.Cuanza_norte.Bolongongo.index')
            @elseif (Auth::user()->municipio == 'Banga')
                @include('extra.centro.Cuanza_norte.Banga.index')
            @elseif (Auth::user()->municipio == 'Samba Cajú')
                @include('extra.centro.Cuanza_norte.Samba_caju.index')
            @elseif (Auth::user()->municipio == 'Gonguembo')
                @include('extra.centro.Cuanza_norte.Ngonguembo.index')
            @endif
        @elseif(Auth::user()->provincia == 'Cuanza Sul')
            @if (Auth::user()->municipio == 'Sumbe')
                @include('extra.centro.cuanza_sul.Sumbe.index')
            @elseif (Auth::user()->municipio == 'Porto Amboim')
                @include('extra.centro.cuanza_sul.Porto_amboim.index')
            @elseif (Auth::user()->municipio == 'Quibala')
                @include('extra.centro.cuanza_sul.Quibala.index')
            @elseif (Auth::user()->municipio == 'Libolo')
                @include('extra.centro.cuanza_sul.Libolo.index')
            @elseif(Auth::user()->municipio == 'Mussende')
                @include('extra.centro.cuanza_sul.Mussende.index')
            @elseif (Auth::user()->municipio == 'Amboim')
                @include('extra.centro.cuanza_sul.Amboim.index')
            @elseif (Auth::user()->municipio == 'Ebo')
                @include('extra.centro.cuanza_sul.Ebo.index')
            @elseif (Auth::user()->municipio == 'Quilenda')
                @include('extra.centro.cuanza_sul.Quilenda.index')
            @elseif (Auth::user()->municipio == 'Conda')
                @include('extra.centro.cuanza_sul.Conda.index')
            @elseif (Auth::user()->municipio == 'Seles')
                @include('extra.centro.cuanza_sul.Seles.index')
            @elseif (Auth::user()->municipio == 'Cela')
                @include('extra.centro.cuanza_sul.Cela.index')
            @elseif (Auth::user()->municipio == 'Cassongue')
                @include('extra.centro.cuanza_sul.Cassongue.index')
            @endif
        @elseif(Auth::user()->provincia == 'Cunene')
            @if (Auth::user()->municipio == 'Cuanhama')
                @include('extra.centro.Cunene.Cuanhama.index')
            @elseif (Auth::user()->municipio == 'Ombadja')
                @include('extra.centro.Cunene.Ombadja.index')
            @elseif (Auth::user()->municipio == 'Cuvelai')
                @include('extra.centro.Cunene.Cuvelai.index')
            @elseif (Auth::user()->municipio == 'Curoca')
                @include('extra.centro.Cunene.Curoca.index')
            @elseif(Auth::user()->municipio == 'Cahama')
                @include('extra.centro.Cunene.Cahama.index')
            @elseif (Auth::user()->municipio == 'Namacunde')
                @include('extra.centro.Cunene.Namacunde.index')
            @elseif (Auth::user()->municipio == 'Xangongo')
                @include('extra.centro.Cunene.Xangongo.index')
            @endif
        @elseif(Auth::user()->provincia == 'Huambo')
            @if (Auth::user()->municipio == 'Huambo')
                @include('extra.centro.Huambo.Huambo.index')
            @elseif (Auth::user()->municipio == 'Londuimbali')
                @include('extra.centro.Huambo.Londuinbali.index')
            @elseif (Auth::user()->municipio == 'Bailundo')
                @include('extra.centro.Huambo.Bailundo.index')
            @elseif (Auth::user()->municipio == 'Chindjenje')
                @include('extra.centro.Huambo.Chinjenje.index')
            @elseif(Auth::user()->municipio == 'Ucuma')
                @include('extra.centro.Huambo.Ucuma.index')
            @elseif (Auth::user()->municipio == 'Ecunha')
                @include('extra.centro.Huambo.Ecunha.index')
            @elseif (Auth::user()->municipio == 'Chicala-Choloanga')
                @include('extra.centro.Huambo.Chicala_cholohanga.index')
            @elseif (Auth::user()->municipio == 'Cachiungo')
                @include('extra.centro.Huambo.Cachilungo.index')
            @elseif (Auth::user()->municipio == 'Longonjo')
                @include('extra.centro.Huambo.Longonjo.index')
            @elseif (Auth::user()->municipio == 'Caála')
                @include('extra.centro.Huambo.Caala.index')
            @endif


<<<<<<< HEAD
            <!--Pedro-->
        @elseif (Auth::user()->provincia == 'Huila')
            @if (Auth::user()->municipio == 'Caconda')
                @include('extra.centro.Huila.Caconda.index')
            @elseif (Auth::user()->municipio == 'Cacula')
                @include('extra.centro.Huila.Cacula.index')
            @elseif (Auth::user()->municipio == 'Caluquembe')
                @include('extra.centro.Huila.Caluquembe.index')
            @elseif (Auth::user()->municipio == 'Chibia')
                @include('extra.centro.Huila.Chibia.index')
            @elseif (Auth::user()->municipio == 'Chicomba')
                @include('extra.centro.Huila.Chicomba.index')
            @elseif (Auth::user()->municipio == 'Chipindo')
                @include('extra.centro.Huila.Chipindo.index')
            @elseif (Auth::user()->municipio == 'Cuvango')
                @include('extra.centro.Huila.Cuvango.index')
            @elseif (Auth::user()->municipio == 'Humpata')
                @include('extra.centro.Huila.Humpata.index')
            @elseif (Auth::user()->municipio == 'Jamba')
                @include('extra.centro.Huila.Jamba.index')
            @elseif (Auth::user()->municipio == 'Lombonjo')
                @include('extra.centro.Huila.Lombonjo.index')
            @elseif (Auth::user()->municipio == 'Lubango')
                @include('extra.centro.Huila.Lubango.index')
            @elseif (Auth::user()->municipio == 'Matala')
                @include('extra.centro.Huila.Matala.index')
            @elseif (Auth::user()->municipio == 'Quilembes')
                @include('extra.centro.Huila.Quilembes.index')
            @elseif (Auth::user()->municipio == 'Quipungo')
                @include('extra.centro.Huila.Quipungo.index')
            @endif
        @elseif(Auth::user()->provincia == 'Luanda')
            @if (Auth::user()->municipio == 'Belas')
                @include('extra.centro.Luanda.Belas.index')
            @elseif (Auth::user()->municipio == 'Cacuaco')
                @include('extra.centro.Luanda.Cacuaco.index')
            @elseif (Auth::user()->municipio == 'Cazenga')
                @include('extra.centro.Luanda.Cazenga.index')
            @elseif (Auth::user()->municipio == 'Estrutura Central')
                @include('extra.centro.Luanda.Estrutura_central.index')
            @elseif (Auth::user()->municipio == 'Icolo e Bengo')
                @include('extra.centro.Luanda.Icolo_e_bengo.index')
            @elseif (Auth::user()->municipio == 'Kilamba Kiaxi')
                @include('extra.centro.Luanda.Kilamba_kiaxi.index')
            @elseif (Auth::user()->municipio == 'Luanda')
                @include('extra.centro.Luanda.Luanda.index')
            @elseif (Auth::user()->municipio == 'Quiçama')
                @include('extra.centro.Luanda.Quicama.index')
            @elseif (Auth::user()->municipio == 'Rangel')
                @include('extra.centro.Luanda.Rangel.index')
            @elseif (Auth::user()->municipio == 'Talatona')
                @include('extra.centro.Luanda.Talatona.index')
            @elseif (Auth::user()->municipio == 'Viana')
                @include('extra.centro.Luanda.Viana.index')
            @endif
        @elseif(Auth::user()->provincia == 'Lunda-Norte')
            @if (Auth::user()->municipio == 'Cambulo')
                @include('extra.centro.Lunda-Norte.Cambulo.index')
            @elseif (Auth::user()->municipio == 'Capenda-Camulemba')
                @include('extra.centro.Lunda-Norte.Capenda_camulemba.index')
            @elseif (Auth::user()->municipio == 'Caungula')
                @include('extra.centro.Lunda-Norte.Caungula.index')
            @elseif (Auth::user()->municipio == 'Chitato')
                @include('extra.centro.Lunda-Norte.Chitato.index')
            @elseif (Auth::user()->municipio == 'Cuango')
                @include('extra.centro.Lunda-Norte.Cuango.index')
            @elseif (Auth::user()->municipio == 'Cuilo')
                @include('extra.centro.Lunda-Norte.Cuilo.index')
            @elseif (Auth::user()->municipio == 'Lóvua')
                @include('extra.centro.Lunda-Norte.Lovua.index')
            @elseif (Auth::user()->municipio == 'Lubalo')
                @include('extra.centro.Lunda-Norte.Lubalo.index')
            @elseif (Auth::user()->municipio == 'Lucapa')
                @include('extra.centro.Lunda-Norte.Lucapa.index')
            @endif
        @elseif(Auth::user()->provincia == 'Lunda-Sul')
            @if (Auth::user()->municipio == 'Cacolo')
                @include('extra.centro.Luanda_sul.Cacolo.index')
            @elseif (Auth::user()->municipio == 'Dala')
                @include('extra.centro.Luanda_sul.Dala.index')
            @elseif (Auth::user()->municipio == 'Muconda')
                @include('extra.centro.Luanda_sul.Muconda.index')
            @elseif (Auth::user()->municipio == 'Saurimo')
                @include('extra.centro.Luanda_sul.Saurimo.index')
            @endif
        @elseif(Auth::user()->provincia == 'Malanje')

@elseif(Auth::user()->provincia == "Malanje")

    @if(Auth::user()->municipio == "Cacuso")
    @include('extra.centro.Malanje.Cacuso.index')
    @elseif (Auth::user()->municipio == "Cahombo")
    @include('extra.centro.Malanje.Cahombo.index')
    @elseif (Auth::user()->municipio == "Calandula")
    @include('extra.centro.Malanje.Calandula.index')
    @elseif (Auth::user()->municipio == "Cambundi-Catembo")
    @include('extra.centro.Malanje.Cambundi_catembo.index')
    @elseif (Auth::user()->municipio == "Cangandala")
    @include('extra.centro.Malanje.Cangandala.index')
    @elseif (Auth::user()->municipio == "Kiwaba-Nzoji")
    @include('extra.centro.Malanje.Kiwaba_nzoji.index')
    @elseif (Auth::user()->municipio == "Luquembo")
    @include('extra.centro.Malanje.Luquembo.index')
    @elseif (Auth::user()->municipio == "Malanje")
    @include('extra.centro.Malanje.Malanje.index')
    @elseif (Auth::user()->municipio == "Marimba")
    @include('extra.centro.Malanje.Marimba.index')
    @elseif (Auth::user()->municipio == "Massango")
    @include('extra.centro.Malanje.Massango.index')
    @elseif (Auth::user()->municipio == "Moxico")
    @include('extra.centro.Malanje.Moxico.index')
    @elseif (Auth::user()->municipio == "Mucari")
    @include('extra.centro.Malanje.Mucari.index')
    @elseif (Auth::user()->municipio == "Quela")
    @include('extra.centro.Malanje.Quela.index')
    @endif

@elseif(Auth::user()->provincia == "Moxico")
@include('extra.centro.Moxico.index')
@elseif(Auth::user()->provincia == "Namibe")
@include('extra.centro.Namibe.index')
@elseif(Auth::user()->provincia == "Uíge")
@include('extra.centro.Uige.index')
@elseif(Auth::user()->provincia == "Zaire")
@include('extra.centro.Zaire.index')
@endif
    </select>
</div>
