<option>[EQT] COMPLEXO ESCOLAR 17 DE SETEMBRO N. 02 - CCD</option>
<option>[EQT] ESCOLA PRIMARIA. ALDEIA KAFULO N. 08 - CCD</option>
<option>[EQT] ESCOLA PRIMÁRIA DA ALDEIA SÁMBIO N. 06 - CCD</option>
<option>[EQT] ESCOLA PRIMÁRIA 1º DE MAIO N. - 01 CCD</option>
<option>[EQT] COMPLEXO ESCOLAR 04 DE FEVEREIRO N. 03 - CCD</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO DIRICO</option>
<option>[EQT] COMPLEXO ESCOLAR N 28 DE AGOSTO   CCD  N 04</option>
