<option data-provincia="Cuanza-Sul">Sumbe</option>
<option data-provincia="Cuanza-Sul">Porto Amboim</option>
<option data-provincia="Cuanza-Sul">Quibala</option>
<option data-provincia="Cuanza-Sul">Libolo</option>
<option data-provincia="Cuanza-Sul">Mussende</option>
<option data-provincia="Cuanza-Sul">Amboim</option>
<option data-provincia="Cuanza-Sul">Ebo</option>
<option data-provincia="Cuanza-Sul">Quilenda</option>
<option data-provincia="Cuanza-Sul">Conda</option>
<option data-provincia="Cuanza-Sul">Seles</option>
<option data-provincia="Cuanza-Sul">Cela</option>
<option data-provincia="Cuanza-Sul">Cassongue</option>
