<option data-provincia="Cuanza sul">Sumbe</option>
<option data-provincia="Cuanza sul">Porto Amboim</option>
<option data-provincia="Cuanza sul">Quibala</option>
<option data-provincia="Cuanza sul">Libolo</option>
<option data-provincia="Cuanza sul">Mussende</option>
<option data-provincia="Cuanza sul">Amboim</option>
<option data-provincia="Cuanza sul">Ebo</option>
<option data-provincia="Cuanza sul">Quilenda</option>
<option data-provincia="Cuanza sul">Conda</option>
<option data-provincia="Cuanza sul">Seles</option>
<option data-provincia="Cuanza sul">Cela</option>
<option data-provincia="Cuanza sul">Cassongue</option>
