<option>[EQT] ESCOLA PRIMÁRIA 17 DE SETEMBO - LONGONJO </option>
<option>[EQT] LICEU Nº 52 LONGONJO</option>
<option>[EQT] DELEGAÇAO MUNICIPAL DO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 88 ENHALA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 71 CANJILA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 69 CHILI LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 56 BUNGUE LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 5 CAMACO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº31 CALUEIO LONGONJO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº19 LÉPI DUMBO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº14 SEDE LÉPI LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 13 EMANHA LONGONJO</option>
<option>[EQT] COLÉGIO Nº 70 BONGO LONGONJO</option>
<option>[EQT] COLEGIO Nº49 SEDE LÉPI LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 63 NAZARÉ LONGONJO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 60 CATABOLA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 1 DR. ANTÓNIO AGOSTINHO NETO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 3 CAPANGO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 86 KULUVIA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 64 SACHINGULO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 43 CAMBUMBULE LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº42 CHICOMO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 39 MOLONJAMBA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 34 CACUCO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº28 CATIVA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº12 CONUSSE LONGONJO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 61 CHILATA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 6 CAWEIE LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 24 YAVA SAMARIA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº23 CATABOLA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 81 CATALI LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 46 AYENJA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 41 ECHOLOLO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 26 CAMBINDA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº21 ELUNDI LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº11 LUCAMBA LONGONJO</option>
<option>[EQT] COLÉGIO Nº 47 COMANDANTE NZAJI LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 4 QUELEBOI LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº74 JILACALIMI LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 50 POUSADA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 44 POVOAÇÃO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 36 ULEMBI LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 82 CATINA LONGONJO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº27 CHILATA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 7 ELAVOCO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº30 SAWATELA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 29 SALUIMBA LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 20 SANDOMBO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 2 CALUNDO LONGONJO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 18 LÉPI CALENGA NJOLO LONGONJO</option>
