<option>[EQT] ESCOLA PRIMÁRIA Nº 32 LOÑGE DE CHIACA - CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº14 WILALA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 43 SAMBUNJO CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 33 ETALAHOLUA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 3 KANDONGO CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 28 -1 DE MAIO CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 2 OMALA - CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº27 KANASSI I CHINJENJE</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 4 JOLOMBA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº38 CHILAMBA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 15 FRANCO CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº15 KAHOMBO I CHINJENJE</option>
<option>[EQT] LICEU REI CILULU VANGUEVANGUE CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 21 SENGA - PRAIA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 42 KACHIQUELA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMARIA Nº 32 KANGUE - CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº29 ALBANO MACHADO CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 8 CHITEMBO CHENJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº1 - 8 DE MARÇO CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 40 CHICALANDONDO CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº35 SAKATU CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 17 DE SETEMBRO - CAMELA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 44 KAPARACASSA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 23 SAKALUNHE CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 56 SANTO CALUTELA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 20 TCHIMBUA CHINJENJE</option>
<option>[EQT] COLÉGIO HÉLDER NETO CHINJENJE</option>
<option>[EQT] ESCOLA DO ENSINO PRIMÁRIO Nº31 SAYAMBO I - CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº37 NDUNDUMA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 55 ETALANGALA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 29 TCHISSEYA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 13 SANGUEVE CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 7 KASSEQUE CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA N.º36 KAMATENDA CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 16 SAYAMBO II CHINJENJE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 1 - DEOLINDA RODRIGUES CHINJENJE</option>
