<option>[EQT] COMPLEXO ESCOLAR PASCOAL GUILHERME CHIWOWO - CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA ANTÓNIO MIÚDO - CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE EROLA - CUROCA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DE EDUCAÇÃO DE CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TAPELA - CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHICOLO - CUROCA</option>
<option>[EQT] COMPLEXO ESCOLAR DE CHITADO - CUROCA</option>
<option>[EQT] LICEU DOUTOR ANTÓNIO DIDALELWA - CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MAMBONDE - CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE WARÚ - CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE RUACANA - CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONDAMBO - CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHITAPAUA - CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIPA - CUROCA</option>
<option>[EQT] ESCOLA PRIMÁRIA 11 DE NOVEMBRO-OMBWA - CUROCA</option>
