<option>[EQT] COMPLEXO ESCOLAR N. 13 FRANCISCO CHIMBUNGO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 115 MISSÃO CATÓLICA FEMININA</option>
<option>[EQT] MAGISTÉRIO N. 297 - ICRA</option>
<option>[EQT] LICEU SAMUEL LUSSATI - CUNJE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 271 MALANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 117 DE PEDRO SALUVOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 131 VIYE - EKOVONGO</option>
<option>[EQT] COMPLEXO BOM DEUS N. 298 - CUITO</option>
<option>[EQT] MAGESTÉRIO MARISTA SÃO JOSÉ - CUITO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 22 SÃO TOMÁS DE AQUINO</option>
<option>[EQT] INSTITUTO POLITÉCNICO DE ADMINI DA CENTRALIDADE H. DO CUÍTO</option>
<option>[EQT] COMPLEXO ESCOLAR N.º 317 REI VIYE - CUITO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 119 BOA ESPERANÇA - CHISSINGUI</option>
<option>[EQT] ESCOLA PRIMARIA N. 256 SOBA CATRAIO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 109 DE LUCIANO SALUCIO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 6 HELENA DE ALMEIDA</option>
<option>[EQT] COLEGIO RER. JÚLIO FRANCISCO MUEHOMBO N. 266</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 86 DE ULOMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 27 SOBA TCHINDUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 157 DE SAVICOTI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 233 DE SAPALO SAMBUINDINGUI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 272 SÃO PEDRO CLÁVER</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 21 DE SANTA ROSA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 70 - PADRE ANTÓNIO DE OLIVEIRA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 79 DE NGUENDELAMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 226 DE CHIPUCA - DOMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 288 DE CHIMBUNDI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 166 DE KAPETA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 289 FRANCISCO CAMBOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 183 BAPTISTA YOANO</option>
<option>[EQT] LICEU N. 292 - 4. DIVISÃO</option>
<option>[EQT] COLÉGIO N. 57 REVERENDO AUGUSTO CHIPESSE</option>
<option>[EQT] COLEGIO N. 275 DO CUÍTO</option>
<option>[EQT] MAGISTÉRIO "CÂNDIDA CELESTE DA SILVA"- CUÍTO/BIÉ</option>
<option>[EQT] COLÉGIO N. 300 CDTE CUSSUMUA</option>
<option>[EQT] GABINETE PROVINCIAL DE EDUCAÇÃO DO BIÉ</option>
<option>[EQT] COMPLEXO ESCOLAR N. 318 PIMPÓLIO CUITO</option>
<option>[EQT] COMPLEXO ESCOLAR CDTE SIMIONE MUCUNE - CENTRALIDADE HORIZONTE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 177 DE VICTOR SALUCOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 59 - CMDTE MARTINS</option>
<option>[EQT] COLÉGIO N. 53 DA CHICALA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 76 - 1 DE MAIO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 137 - 2 DE MARÇO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 274 ANTÓNIO DA FONSECA</option>
<option>[EQT] LICEU N. 290 - REI NDUNDUMA</option>
<option>[EQT] INSTITUTO TÉCNICO DE SAUDE N. 295 - CDTE BULA</option>
<option>[EQT] COLÉGIO N. 78 JAMBA - YA - MINA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 65 NOSSA SENHORA DA PAZ</option>
<option>[EQT] COLÉGIO N. 175 - CDTE KATALECO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 133 PE. AGOSTINHO VERÍSSIMO SONJAMBA</option>
<option>[EQT] COLÉGIO N. 302 - CDTE REGRESSO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CUITO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 60 04 DE JANEIRO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 24 - 14 DE ABRIL</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 51 DE CAPOLO</option>
<option>[EQT] COMPLEXO ESCOLAR ENSINO ESPECIAL N. 271</option>
<option>[EQT] COMPLEXO ESCOLAR N. 14 CDTE CUSSUMUA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 74 ESTRELA DA MANHÃ</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 03 DE ANDRÉ COLE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 37 GINGA MBANDI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 223 NGONGA CHIANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 7 MUTU - YA - KEVELA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 16 FELIZBERTO NGUNGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 255 DE ANTUNES CAPUSSO</option>
<option>[EQT] COLÉGIO N. 41 - 17 SETEMBRO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 50 ANTÓNIO CHISSAPA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 303 - DR. FERNANDO SAMUEL PEQUENINO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 94 - HOSSI</option>
<option>[EQT] ESCOLA PRIMÁRIA 25 DE MAIO N. 28 - MUCUMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 157 REI SASSUANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 230 DE TANDAVALA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 180 DE JAIME CAPENDA</option>
<option>[EQT] COLÉGIO N. 38 REI LIAVENDA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 314 - 28 DE JUNHO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 8 - HOJI - YA - HENDA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 264 DE EPONGOLOCO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 148 MISSÃO CAMUNDONGO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 30 ANA MARIA FIDALGA</option>
<option>[EQT] ESCOLA PRIMÁRIA 22 DE NOVEMBRO N. 61</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 168 DE SAMALINHA</option>
<option>[EQT] COLÉGIO N. 215 DE BRUGALHO CHIPEPE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 188 RAINHA TELEIA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 258 DE NGULUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 4 REI FECA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 11 JOAQUIM KAPANGO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 33 DE CANOMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 71 - KAMBELE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 26 CDTE KAYUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 17 CDTE MAD. KALANDULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 56 LUMBO</option>
<option>[EQT] ESCOLA PRIMÁRIO N 270 COMANDANTE TIGRE</option>
<option>[EQT] COLÉGIO N. 236 DR. JOÃO ANDEREU COLE</option>
<option>[EQT] COLÉGIO N. 67 - MANGUXI</option>
<option>[EQT] COLÉGIO N. 69 - CDTE NOVENTA</option>
<option>[EQT] COLÉGIO N. 312 CHARLES DONALD E NAOMI COLE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHITEQUE</option>
<option>[EQT] ESCOLA PRIMÁRIA MISSIONÁRIA N.124</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 269 DE CHIMUNGO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 268 SEBASTIANA GARCIA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 2 ANTÓNIA J. SILVA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 55 - ECOLELO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 10 MISSÃO CHANHORA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 301 SOBA RUBEN LUVENI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 75 SANTA CLARA DE ASSIS</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 82 DE SAMALENGUE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 198 UNIDA DE SACHUMA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 232 DE SANJIMI - UNHAMO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 47 DE GINGA - KUVO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 88</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MANGO N. 129</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 222 JOAQUIM SANDOMBUA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 279 DE MARTINHO SACHILULO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 85 DE CALIQUI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 206 NGANDAVILA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 141 CENTRO NJELE</option>
<option>[EQT] ESCOLA PRIMARIA N. 15 NOSSA SENHORA DO CARMO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 95 DE CASTRO MOMA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 125 DE BÂNDUA</option>
<option>[EQT] COLÉGIO N. 66 - 4 DE ABRIL</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 273 - CHIPUPILI</option>
<option>[EQT] ESCOLS PRIMÁRIA N. 224 DR. JOÃO ANDEREU COLE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 19 DR. SAVITENDELA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 238 DE VIRIATO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 178 REI CUFA</option>
<option>[EQT] ESCOLA PRIM.ÁRIA N. 153 DE CONSTANTINO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 282 DE EMBALA TRUMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 12 - 16 DE JUNHO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 68 - CRIANÇA FUTURO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 25 DE CHIVANGO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 77 CALUCO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 143 DE BUNDI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 31 AUGUSTO NGANGULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 32 DR. ANTÓNIO AGOSTINHO NETO</option>
<option>[EQT] COLÉGIO N. 98 DE KAMBÂNDUA</option>
<option>[EQT] INSTITUTO POLITÉCNICO DE ADMINISTRAÇÃO E GESTÃO DO CUITO - BIÉ</option>
<option>[EQT] COMPLEXO ESCOLAR N. 9 CLEMENTE VINIOMBO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 63 - E.M.I.E.I.A</option>
<option>[EQT] COMPLEXO ESCOLAR N. 110 DE EBENÉZER</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 136 JOÃO CANJUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 277 DE JAMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 122 - CHILEMO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 127 - 11 DE NOVEMBRO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 29 SÃO JOSÉ DE CACHINGUES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 229 JORGE LUPILI</option>
<option>[EQT] COMPLEXO ESCOLAR 10 DE DEZEMBRO N. 48 - CUITO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 5 NOSSA SENHORA DE FÁTIMA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 42 DEOLINDA RODRIGUES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 91 DE WANGA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 169 DE NDULO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 145 DE SAMBOVO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 139 - MÁRTIRES DO KUITO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 58 - E.M.I.E.I.A</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 156 DE CHOMBELA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 117 PEDRO SALUVOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 1 NOVA CANTÍFLAS</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 154 DE CHIVANGULULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 140 DE SANTO AFONSO PRAIA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 36 ADRIANO KAPUMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 267 REI EKWIKWI II</option>
<option>[EQT] INSTITUTO POLITÉCNICO DE GESTÃO DA CENTRALIDADE H. DO CUÍTO</option>
