<option>[EQT] ESCOLA PRIMÁRIA 17 DE SETEMBRO/CATABOLA</option>
<option>[EQT] MAGISTÉRIO 13 DE JULHO - SEDE/CATABOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LUCATA -  SEDE/CATABOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA SOBA SALOMÃO CANICA/SANDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHITEQUE/CHIPETA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHICUNDO/SANDE</option>
<option>[EQT] ESCOLA PRIMARIA DE CHILALO/CHIUCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHISSENDE-KEU-KAPIÑALA/CHIPETA </option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 60 SEDE/CHIPETA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE 7 CASAS - 1 DE JUNHO/CHIPETA</option>
<option>[EQT] ESCOLA PRIMÁRIA - Bº POPULAR/CHIPETA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MISSENE/MUQUINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BELCHIOR/CHIPETA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 280 BAPTISTA CHIKUEKUE/ÚYUE</option>
<option>[EQT] ESCOLA PRIMÁRIA  Nº 281 ÚYUE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 56  CAMUXITO - SEDE/CATABOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CALUSSIMBA/SANDE</option>
<option>[EQT] ESCOLA PRIMÁRIA  Nº 57  OMBALA CACUNHO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MINGUNGO/CAIUERA </option>
<option>[EQT] LICEU FELIZBERTO DOMINGOS NGUNGA/CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR SÃO TOMÁS SANDUNDO/CHINJOIA</option>
<option>[EQT] COMPLEXO ESCOLAR - REV. COSTA ULO/SACHONDI</option>
<option>[EQT] COMPLEXO ESCOLAR DO Iº E IIº CICLO 4 DE ABRIL/CAIUERA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIMBUIO - SEDE/CATABOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE WIYA/CHIPETA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CASSUMBA/SANDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BONGA /SANDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMBALA CHITALELA - SEDE/CATABOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CANDIMBA/MUQUINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA OLIVEIRA SUKUMA/MOMA </option>
<option>[EQT] MAGISTÉRIO PRIMÁRIO 13 DE JULHO/ CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR DO Iº E IIº CICLO PACAÇA ALEIJADA</option>
<option>[EQT] COMPLEXO ESCOLAR SOBA WANGO WONJAMBA/CATABOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAHUMA/CAIUERA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SASSONGO/CHIPETA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE DENDE-SEDE/CATABOLA </option>
<option>[EQT] ESCOLA PRIMÁRIA - LAURINDO NGAYETA/NGUMBE </option>
<option>[EQT] ESCOLA PRIMÁRIA 16 DE JUNHO MBULO/CAIUERA</option>
<option>[EQT] COMPLEXO ESCOLAR DO Iº E IIº CÍCLO SOBA CANJUNDO/CHIUCA</option>
<option>[EQT] COMPLEXO ESCOLA DE OMBALA CHISSENDE-SEDE/CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR 4 DE FEVEREIRO/MUQUINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MUTIETIE/CHIUCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BIMBI/SEDE-CATABOLA </option>
<option>[EQT] COMPLEXO ESCOLA - REV. LUMBO/MISSÃO CHISSAMBA </option>
<option>[EQT] ESCOLA PRIMÁRIA  MATEUS CHICANHA/CAIUERA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 69 - SEDE/CATABOLA</option>
<option>[EQT] ECOLA PRIMÁRIA SEDE CHIUCA</option>
<option>[EQT] ESCOLA PRIMÁRIA - MAQUINA CAIOMBO - SEDE/CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR - 11 DE NOVEMBRO/CHICUMBI</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SANANGA/CHIUCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DA SEDE - SANDE/CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR DE SÃO LUCAS - SEDE/CATABOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SAMASSECA-SEDE/CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR 22 NOVEMBRO/SACHIWALA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SACHINGONGO/CAIUERA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NGONDE-SEDE/CATABOLA</option>
<option>[EQT] COLÉGIO PATRICE LUMUMBA - SEDE/CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR FERNANDO NANGA/CAIUERA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 55 AUGUSTO NGANGULA - SEDE/CATABOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CALILA/CHIPEDA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR DE ENTRE - RIOS/CHIUCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAQUENGUE/MUQUINDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMBALA CHIUCA/CATABOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAPOCO/CHIUCA</option>
<option>[EQT] COMPLEXO ESCOLAR DE CAJUNGO/CHIPETA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SANAMBELO-SEDE/CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR 4 DE JANEIRO/SANDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CALOHANDA - SEDE/CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR "CDT"SIMIONE MUCUME - CATABOLA</option>
<option>[EQT] COMPLEXO ESCOLAR ESSACA LIANJIMBI - SEDE/CATABOLA</option>
<option>[EQT] ESCOLA DE MAGISTÉRIO ADPP -CATABOLA/BIÉ</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 61 LONDELA INDUSTRIAL -SEDE/CATABOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHINHULO/CHIUCA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE COMPÃO-SEDE/CATABOLA</option>
<option>[EQT] COLÉGIO TÉCNICO DE PRÁTICAS AGRÁRIAS - SEDE/CATABOLA</option>
