<option>[EQT] ESCOLA PRIMÁRIA DA LONDA - AMBOIM</option>
<option>[EQT] ESCOLAR PRIMÁRIA PADRE MAIA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA SOBA QUIPUNA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA RENASCER - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA MUTU - YA - KEVELA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA HONGA BANZA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA AFRICANA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA COMANDANTE DANGEREUX - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 4 DE ABRIL - GIRAÚL - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 354 DO ASSANGO - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 11 DE NOVEMBRO - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA SAIDY MINGAS - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA QUICUNDA I - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA PATRICE LUMUMBA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA NGOLA KILUANGE - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA JOSÉ MARTY - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO SANGUÉ - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO QUIPAXE - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO BRUVIL - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 17 DE SETEMBRO - AMBOIM</option>
<option>[EQT] COMPLEXO ESCOLAR 1º DE MAIO ARICANGA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA NZINGA MBANDI - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA CALEMBA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA AUGUSTO NGANGULA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO ICA CAPANGA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA MACARENKO - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA LUZ E ÁGUA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA CALONGA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA ALDEIA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA HERÓIS DE CANGAMBA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA QUICUNDA DE BAIXO II - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO PANGE - AMBOIM</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA NOVA EREIRA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA CATUTA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA COMANDANTE ARGUELLES - AMBOIM</option>
<option>[EQT] COLÉGIO HERÓIS DO CUITO CUANAVALE - AMBOIM</option>
<option>[EQT] COMPLEXO ESCOLAR BOA ENTRADA - CADÁ - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA HOJI YA HENDA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO QUIPUNGO - AMBOIM</option>
<option>[EQT] INSTITUTO POLITÉCNICO DA GABELA - AMBOIM</option>
<option>[EQT] COMPLEXO ESCOLAR DO ASSANGO - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA BELA VISTA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA BOA VIAGEM - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 4 DE FEVEREIRO - QUINA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA POVO UNIDO - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA GARCIA NETO - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO GIA - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CAPANGO - AMBOIM</option>
<option>[EQT] COMPLEXO ESCOLAR DOUTOR ANTÓNIO AGOSTINHO NETO - AMBOIM</option>
<option>[EQT] MAGISTÉRIO DO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 22 DE NOVEMBRO - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA REI MANDUME - SALINAS - AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA NELITO SOARES - HUIA - AMBOIM</option>
