<option>[EQT] ESCOLA PRIMÁRIA N. 9 - QUIXINGA - KUNDA DYA BAZE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 8 - MÁQUINA - KUNDA DYA BAZE</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE KUNDA DYA BAZE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº05 ISSANGA-TECA - KUNDA DYA BAZE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº02 CAFU- KUNDA DYA BAZE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 06 - DR. ANTÓNIO AGOSTINHO NETO- KUNDA </option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 01 LEMBA - KUNDA DYA BAZE</option>
<option>[EQT] COLÉGIO N. 07 - MÁRTIRES DA BAIXA DE CASSANJE- KUNDA DYA BAZ</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 4 - MILANDO - KUNDA DYA BAZE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº03 QUIZENGA - KUNDA DYA BAZE</option>
