<option>[EQT] ESCOLA PRIMÁRIA DE CHISSUATA - MALONGA - CAMICHA  SACHINJAMB</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHANA CUELEI E TCHIYONGOYONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 408 DE CAPANGO - CHIPICA E MIVEVA</option>
<option>[EQT] COMPLEXO ESCOLAR MISSIONÁRIO SÃO JOÃO BAPTISTA</option>
<option>[EQT] COMPLEXO ESCOLAR 17 DE SETEMBRO-CHITEMBO</option>
<option>[EQT] COMPLEXO ESCOLAR DO MUTUMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NDUNGULA - CHITEMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHINGUEIA-SOVI-CUSSEQUE E CALOMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE WATANA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 412 DE NHAHONDOLA - UTALE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMBINDA - CHICUMA E CHIVONGO</option>
<option>[EQT] COMPIEXO ESCOLAR DE JAMBA - YA - NGANDZI</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 121 - MUINI NDUMBU E CHIHONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO NGOLO - CHISSEIA E JAMBA -YA-KASSISSI</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MANGA E MACOVA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO BAIRRO PILOTO</option>
<option>[EQT] ESCOLA PRIMÁRIA - 11 DE NOVEMBRO - CHITEMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAWENDE-CHIWANO-CHIVINDA E CAMBUNDI</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAPEMBE-CULANDA-HUAMBO E CHELECA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MUANDUMBA E SENZE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE EMBALA LIAZEMBA E MINGOMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 411 COMANDANTE CHICUECUE E CAUEUE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIAMBA E CUAMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ZEQUITA E CHIPENDE</option>
<option>[EQT] ESCOLA PRIMÁRIA  MUTU - YA - KEVELA CHITEMBO</option>
<option>[EQT] COLÉGIO 10 DE DEZEMBRO - CHITEMBO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CHITEMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 409 - MUMBUÉ</option>
<option>[EQT] ESCOLA PRIMARIA DE SAMALESSO E CATOTI</option>
<option>[EQT] MAGISTÉRIO DO CHITEMBO</option>
<option>[EQT] COMPLEXO ESCOLAR DE MALENGUE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 410 - 1º DE MAIO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE EMBALA MALENGUE E CASSONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SÃO JOSÉ E TAPA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BOA ESPERANÇA-CHISSAMBA-CATAMBUE E MATALA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NJIVA E TCHINTIENGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHICUNDO-VISSUMBA-MIHIATO1 E VINHATI</option>
<option>[EQT] COLÉGIO 4 DE FEVEREIRO - CHITEMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHILEMO - CAPALANDANDA - VINUCO  VINDANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DR. ANTÓNIO AGOSTINHO NETO - CHITEMBO</option>
<option>[EQT] ESCOLA  PRIMÁRIA DE CAWE E LINGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 127 SAGRADA ESPERANÇA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHICONGUELE-CAMBIMBIA-LIVUVU-CHISSILO</option>
<option>[EQT] ESCOLA MISSIONÁRIA DO ENSINO PRIMÁRIO DE CATOTA</option>
<option>[EQT] ESCOLA MISSIONÁRIA DO ENSINO PRIMÁRIO DA I.E.C.A - NOVA VIDA</option>
