<option>[EQT] ESCOLA PRIMÁRIA N. 05 CCC2 - CAMBUMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 15 CCC2 SAVATE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 01 CCC2  CUANGUAR 1</option>
<option>[EQT] COMPLEXO ESCOLAR N. 14 CCC2 SAVATE</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CUANGAR</option>
<option>[EQT] COMPLEXO ESCOLAR N 02CCC2 DO CUANGAR</option>
<option>[EQT] COMPLEXO ESCOLAR N. 10 CCC2 - CAILA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 12 CCC2 -OLUPALE</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 04 CCC2 DO MANGONDO</option>
