<option>[EQT] COMPLEXO ESCOLAR N. 35 CCM2 REV. ABRAÃO NGULU-IECA BAIRRO PAZ</option>
<option>[EQT] COMPLEXO ESCOLAR N. 44 CCM2 - ESPERANÇA DO POVO KATEKE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 66 CCM2 DO SÃO PAULO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 97 CCM2 - CAZENGA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 33 CCM2 - SANTA ISABEL</option>
<option>[EQT] COMPLEXO ESCOLAR N. 101 CCM2 - ADVENTISTA DO 7º DIA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº. 45 CCM2 - MUCUNHA VIOTO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 102 CCM2 ECUMBI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 21 CCM2 DO CAQUINDO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 58 CCM2 - SACAHETA</option>
<option>[EQT] ESCOLA DO MAGISTÉRIO Nº. 79 CCM2 - MWENE VUNONGUE</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 50 CCM2 - 28 DE AGOSTO - BANDA - VELHA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 90 MULEMBA DA PAZ DA FÉ APOSTÓLICA DE BEREIA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 61 CCM2 - KULOTA KUAMENE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 34 CCM2 - DO BOA VENTURA - 23 DE MARÇO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 92 CCM2 - SENGA SAVIPANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 08 CCM2 - SAMUEL</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 36 CCM2-TCHIVONDE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 88 CCM2 - HAVEMOS DE VOLTAR</option>
<option>[EQT] COMPLEXO ESCOLAR Nº. 76 CCM2 DO B. BENFICA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 29 CCM2 - 10 DE DEZEMBRO</option>
<option>[EQT] ESCOLA PRIMÁRIA N.66 CCM2 - SAO PAULO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 89 CCM2 - HOJI-YA-HENDA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 10 CCM2 - TOMÁS</option>
<option>[EQT] ESCOLA DE MAGISTÉRIO ADPP - CUANDO CUBANGO N. 41 CCM2 - MENONGUE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 05 CCM2 - DA MISSÃO CATÓLICA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 02 CCM2 - BOLSA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 82 CCM2 - VICTORIA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 47 CCM2 - JOÃO CAZEQUEMBA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 105 CCM2 - MUENE MUCUVA</option>
<option>[EQT] COLÉGIO N. 14 CCM2 - BALOMBO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 25 PERPÉTUO SOCORRO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 15 CCM2 - DO JAMBA CUEIO</option>
<option>[EQT] COMPLEXO  ESCOLAR N. 22 - CAMBUMBE - NOVO</option>
<option>[EQT] ESCOLA DO ENSINO PRIMÁRIO N. 07 DO POPULAR</option>
<option>[EQT] COMPLEXO ESCOLAR N. 24 - CCM2 - COMANDANTE - HOJI-YA-HENDA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 48 CCM2 - GENERAL EUSEBIO SOBA MATIAS</option>
<option>[EQT] ESCOLA PRIMÁRIA PRIMÁRIA N. 87 CCM2 - B. PAZ</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 67 CCM2 DO KAVANGA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 27 CCM2 DO LUMETA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 30 CCM2 - 17 DE SETEMBRO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 13 CCM2 - NINHO DA PAZ</option>
<option>[EQT] COMPLEXO ESCOLAR N. 04 CCM2 - MANJOLO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 03 CCM2 - GABRIEL MATIAS - B. SAÚDE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 85 CCM2 - MBIMBI</option>
<option>[EQT] COMPLEXO ESCOLAR N. 31 - CCM2 - CRISTO REI</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 53 CCM2 DO MUCUNDI</option>
<option>[EQT] COMPLEXO ESCOLAR  N 94 11 DE NOVEMBRO - IECA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 26 CCM2 - MBEMBWA</option>
<option>[EQT] COMPLEXO ESCOLAR CCM2 - N. 52 - CILINDRO</option>
<option>[EQT] COMPLEXO ESCOLR N. 77 CCM2 - ALBANO ANDRÉ</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 59 CCM2 - CAMUNGAMBA</option>
<option>[EQT] GABINETE PROVINCIAL DE EDUCAÇÃO</option>
<option>[EQT] INST. POLIT. DE ADMINIST. E GESTÃO Nº 39 CCM2, 23 DE MARÇO </option>
<option>[EQT] COMPLEXO ESCOLAR N. 106 CCM2 - SEQUE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 84 CCM2 - MAVINDA BOA - VIDA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 32 CCM2 DA FUTURO DA NAÇÃO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DE EDUCAÇÃO DE MENONGUE</option>
<option>[EQT] INSTITUTO MÉDIO AGRÁRIO N. 42 CCM2 DE MISSOMBO - MENONGUE</option>
<option>[EQT] ESCOLA DE TECNICO DE SAUDE - MENONGUE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 12 CCM2 - CAIUNDO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 06 CCM2 DO PANDERA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 09 CCM2 TRIBUNA DO POVO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 83 CCM2 - KUATIR</option>
<option>[EQT] COMPLEXO ESCOLAR DE INCLUSÃO N. 65 CCM2 - MWENE TCHICOMBA</option>
<option>[EQT] INSTITUTO POLITÉCNICO DO AMBIENTE 31 DE JANEIRO</option>
<option>[EQT] LICEU N. 80 CCM2 - 22 DE NOVEMBRO DE MENONGUE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 23 CCM2 SÃO JOSÉ</option>
<option>[EQT] COMPLEXO ESCOLAR N. 81 CCM2 - TCHIPOMPO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 20 CCM2 - DUMBO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 37 CCM2 - TCHIHONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 57 CCM2 8 DE MARÇO DO NTOPA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 86 CCM2 - DR. AGOSTINHO NETO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 17 - CCM2 - SÃO - KIZITO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 63 CCM2 BOM PASTOR</option>
<option>[EQT] ESCOLA DO ENSINO PRIMÁRIO CCM2 Nº. 11 – ZONDE</option>
<option>[EQT] COMPLEXO ESCOLAR N. 16 CCM2 - KUELEI</option>
<option>[EQT] COMPLEXO ESCOLAR Nº. 43 - MISSOMBO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 01 CCM2 - 4 DE FEVEREIRO</option>
