<option>[EQT] ESCOLA PRIMÁRIA DE OSHIKUKU II - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKALWA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHINDUNGULU - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA OIFANYAMA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA OMBALA-YA-MPINGA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA 17 DE SETEMBRO DE OKAPANGU - CUANHAMA</option>
<option>[EQT] COMPLEXO ESCOLAR BOLETH SALLÚ - ONDJIVA</option>
<option>[EQT] ESCOLA PRIMÁRIA 4 DE ABRIL DE ONDJIVA - CUANHAMA</option>
<option>[EQT] GABINETE PROVINCIAL DA EDUCAÇÃO DO CUNENE</option>
<option>[EQT] INSTITUTO POLITÉCNICO DE NAMAYAKA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHUUMBILA -CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKATALE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHIKUKU I - CUANHAMA</option>
<option>[EQT] INSTITUTO TÉCNICO DE SAÚDE DE ONDJIVA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONANGHWE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BULUNGANGA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHAKATI SHEEMBE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DOS CASTILHOS - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE  MARTINS MBUENA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA JOAQUIM KASSANGA - DE OMALA - CUANHAMA</option>
<option>[EQT] COLÉGIO DE ANHANCA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHIFIDI - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHINGANDU -CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONAMUKA - CUANHAMA</option>
<option>[EQT] COMPLEXO ESCOLAR JOSÉ SILIKEVAMWE DE OKAPANGU - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OFENDA - MÔNGUA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OLUKANGO II - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMINDA I - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA REI NANDE-YA-HEDIMBI - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAPALE II - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONDOBE - CUANHAMA</option>
<option>[EQT] COLÉGIO DE OKAFIMA - CUANHAMA</option>
<option>[EQT] COMPLEXO ESCOLAR DE OULONDELO - ONDJIVA</option>
<option>[EQT] ESCOLA PRIMÁRIA 22 DE NOVEMBRO - ONAKHUMBA II - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMUKWA - CUANHAMA</option>
<option>[EQT] LICEU EIFFEL DE ONDJIVA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMUFITU-UNENE II -CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONGHENDJO - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE EKO PARÓQUIA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHIVAMBI - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OUPYAKADI - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHIMUKWA - CUANHAMA</option>
<option>[EQT] COLÉGIO DE OKAMBADA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA OKAMUTUNDUNGU - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHITANDO - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA TOMÁS MUPAKELENI NAMBONGA DE OHENDA-CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAOLO KANGONGOLO - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAPANDA - CUANHAMA</option>
<option>[EQT] COLÉGIO COMANDANTE COW-BOY - ONDJIVA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMALYATA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DA CAXILA II - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMUVANDJE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONAMAYAKA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NEHONE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA 4 DE JANEIRO DE ONDJIVA - CUANHAMA</option>
<option>[EQT] COLÉGIO DA MÔNGUA - SEDE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OONGO - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OHAUTUKU CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OYONDE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DOM FERNANDO GUIMARÃES KEVANU - OMILUNGA </option>
<option>[EQT] ESCOLA PRIMÁRIA DE ELALA - CUANHAMA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OUKWANGHULA - CUANHAMA</option>
<option>[EQT] ESCOLA DO ENSINO ESPECIAL RAINHA NEKOTO - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº56 - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONANYAMA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONDJABULA - CUANHAMA</option>
<option>[EQT] COLÉGIO DA MISSÃO CATÓLICA DE OMILUNGA - CUANHAMA</option>
<option>[EQT] INSTITUTO POLITÉCNICO DE ADMINISTRAÇÃO E GESTÃO - ONDJIVA.</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHIDIVA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OIMWANDI - CUANHAMA</option>
<option>[EQT] COLÉGIO DE OIFIDI - CUANHAMA</option>
<option>[EQT] MAGISTÉRIO DR. ANTÓNIO AGOSTINHO NETO - ONDJIVA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAPAKUPAKU - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAFUKA I - CUANHAMA</option>
<option>[EQT] COLÉGIO DE OUPYAKADI - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMUDIVA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHOMUKUIYU - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMUNDJOWI - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OHEPUKA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONAMEVA I - CUANHAMA</option>
<option>[EQT] COLÉGIO DE OIPEMBE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMBALA GRANDE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OIDIVA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NDAPONA-YA-SIKENDE DA MÔNGUA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OHAKUYELA ONAXUI - CUANHAMA</option>
<option>[EQT] COMPLEXO ESCOLAR REI WEYULU-YA-HEDIMBI "CAXILA III "- ONDJIV</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHILIMBALA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE EMANHA -CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONGHUMBO - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE EDIVA LONGHOSHI - CUANHAMA</option>
<option>[EQT] COMPLEXO ESCOLAR PADRE CARLOS MITTELBERGER - OMUPANDA</option>
<option>[EQT] COLÉGIO DA MISSÃO CATÓLICA DE OMUDIVA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHIHAMBO - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ENGHUSHE -CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONDOVA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA 28 DE AGOSTO DE OIFIDI - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OLUKEKETE - CUANHAMA</option>
<option>[EQT] MAGISTÉRIO DE OIFIDI - ADPP - CUNENE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMBELWA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OHENGHALI II - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE EHAFO II - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMUTAKU - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAFITU III - CUANHAMA</option>
<option>[EQT] COMPLEXO ESCOLAR SHEEFENI-SHA-MUKWIYU "OKAPALE II"- ONDJIVA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OULONDELO - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONAMBWEKHUMBI - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAMUKWA II - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHIKHUNGA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OUTOKELO - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE EKUMA I - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ENGHOLO - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº254 - CUANHAMA</option>
<option>[EQT] COLÉGIO DE OMALA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAHENGE I - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA 8 DE JANEIRO - ONAKHUMBA I - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OSHITUMBA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ETWATWA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONYALUHEKE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAPUNDUKA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAFIMA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OHAKAONDE - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº2 DE ANHANCA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAMBADA - CUANHAMA</option>
<option>[EQT] COLÉGIO DE ONAMEVA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKOMBILI - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONYANGA II - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMBUBA - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 122 - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONDJEDI - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OKAPALE I - CUANHAMA</option>

<option>[EQT] ESCOLA PRIMÁRIA N.º 122 - CUANHAMA</option>
<option>[EQT] ESCOLA PRIMÁRIA RAINHA NEKOTO - CUANHAMA</option>
<option>[EQT] ESCOLA DA CENTRALIDADE DOM GUIMARÃES - CUANHAMA</option>
<option>[EQT] COMPLEXO ESCOLAR SHEEFENI-SHA-MUKUIYU - CUANHAMA</option>