<option>[EQT] ESCOLA PRIMÁRIA BG 1013 - CAMBANDA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1027 - CALOHOMBO - BENGUELA</option>
<option>[EQT] COLÉGIO BG 1084 - GRAÇA - BENGUELA</option>
<option>[EQT] MAGISTÉRIO BG 1085 - PARÓQUIA DE SANTO ESTÊVÃO - BENGUELA</option>
<option>[EQT] COLÉGIO BG 1000 - BAIRRO DO SETENTA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1128 - PARÓQUIA SANTO ESTEVÃO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1040 - 4 DE ABRIL - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1127 - BAIRRO HOJI-YA-HENDA - BENGUELA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1087 - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1111 BAIRRO ATLÂNTICO - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1025 - BAIRRO 11 DE NOVEMBRO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1126 - BAIRRO DO EKWIKWI II - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1327 - DEOLINDA RODRIGUES - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1046 - 17 DE SETEMBRO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1110 - DR. A. AGOSTINHO NETO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1049 - BAIRRO VIVA PAZ - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1024 - PARÓQUIA SANTO ESTEVÃO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1050 - CASSÔCO - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1008 - BENGUELA </option>
<option>[EQT] COMPLEXO ESCOLAR BG 1011 - JOAQUIM KAPANGO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1001 - NICOLAU GOMES SPENCER - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1053 - SETA - BENGUELA</option>
<option>[EQT] COLÉGIO BG 1037 - CDTE AUGUSTO CHIPENDA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1082 - COTEL - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1348 - LUÍS GOMES SAMBO - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1052 - NOSSA SRª DA CONCEIÇÃO - BENGUELA</option>
<option>[EQT] COLÉGIO BG 1080  - VALE DE BÊNÇÃO - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1044 - POSSOCA - IMUA - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1114 - FORMIGAS DO FUTURO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1006 - KALOSSOMBÉKWA II - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1116 - BAIRRO DO KALOMBUTÃO - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1066 - TCHIPIANDALO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1069 - KAMBANGELA - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1076 - PENITÊNCIÁRIA - BENGUELA</option>
<option>[EQT] COLÉGIO BG 1115 - 10 DE FEVEREIRO - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1009 - QUIOCHE - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1032 - CAÓTA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1033 - BAÍA DO STO. ANTÓNIO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1007 - LIXEIRA - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1079 - CASA DO GAIATO - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1239 - NOSSA SRA. DA GRAÇA - BENGUELA</option>
<option>[EQT] MAGISTÉRIO BG 1022 - LÚCIA LARA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1018 - CANDUMBO - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1077 - HERMANN GMNEIR - SOS - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1163 - MAJOR SAIDY V. MINGAS - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1028 - KASSEQUE MARÍTIMO - BENGUEL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1036 - KASSEQUE MACAU - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1067 - TAKA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1122 - BAIRRO DO SETENTA - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1237 - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1252 - ALDA LARA - BENGUELA</option>
<option>[EQT] MAGISTÉRIO BG 1045 - DOM BOSCO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1055 - KALOMANGA - BENGUELA</option>
<option>[EQT] INSTITUTO TÉC. BG 1162 - Nª SRA. MÃE SABEDORIA-ICRA BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1039 - UCHI - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1108 - STA TEREZINHA M. JESUS - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1035 - BELA VISTA BAIXA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1023 - 11 DE NOVEMBRO - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1005 - NOSSA SRª DA NAZARÉ - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1109 - BENFICA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1117 - BAIRRO DA KAMANIÑGA II - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1078 - IRMÃS FRANCISCANAS - BENGUELA </option>
<option>[EQT] COMPLEXO ESCOLAR BG 1014 - EX- COLÉGIO ANGOLANO - BENGUELA</option>
<option>[EQT] COLÉGIO BG 1061 - 22 DE NOVEMBRO - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1065 - KALOMBURACO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1068 - MINA - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1083 - SEDE DE SABEDORIA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1072 - KAPILONGO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1048 - TALAMAJAMBA - BENGUELA</option>
<option>[EQT] MAGISTÉRIO BG 1075 - ADPP - BENGUELA</option>
<option>[EQT] GABINETE PROVINCIAL DA EDUCAÇÃO DE BENGUELA</option>
<option>[EQT] ESCOLA TÉCNICA BG 1086 - ADPP - BENGUELA</option>
<option>[EQT] COLÉGIO BG 1056 -  CDTE. TOMÁS FERREIRA - BENGUELA</option>
<option>[EQT] INSTITUTO POLITÉCNICO BG 1074 - GRAÇA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1003 - UTOMBA - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1004 - KALOSSOMBEKWA I - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1123 - GOA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1002 - HOJI-YA-HENDA - BENGUELA </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1070 - KAWANGO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1063 - SÃO TIAGO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1030 - BAIRRO DO KALOSSONGO - BENGUELA</option>
<option>[EQT] COLÉGIO BG 1012 - PAULO TEIXEIRA JORGE - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1064 - DAMBA MARIA - BENGUELA</option>
<option>[EQT] INSTITUTO POLITÉCNICO BG 1020 - INDUSTRIAL - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1038 - ENSINO ESPECIAL - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1073 - UKENDY - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1047 - LAURA VICUÑA - BENGUELA</option>
<option>[EQT] INSTITUTO TÉCNICO BG 1125 - HOTELARIA E TURISMO - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1071 - BAIRRO DA GRAÇA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1113 - BAIRRO DO DOKOTA - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1059 - PARÓQUIA SANTO ANTÓNIO - BENGUELA</option>
<option>[EQT] COLÉGIO BG 1118 - KASSEQUE I - BENGUELA</option>
<option>[EQT] LICEU BG 1062 - MASSANGARALA - BENGUELA</option>
<option>[EQT] INSTITUTO TÉCNICO ADM. SERV BG 1015 CDTE KASSANJI - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1026 - 4 FEVEREIRO - BENGUELA</option>
<option>[EQT] INSTITUTO TÉCNICO AGRÁRIO BG 1019 - JOAQUIM KAPANGO-BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1043 - BAIRRO ESPERANÇA - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1120 - NAIM - BENGUELA </option>
<option>[EQT] COLÉGIO BG 1041 - NAVEGANTES - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1029 - KASSEQUE - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1010 - BAIRRO SETENTA E UM - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1034 - BELA VISTA ALTA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1328 - FRONTEIRA - BENGUELA</option>
<option>[EQT] INSTITUTO TÉCNICO DE SAÚDE BG 1081 - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1112 - BAIRRO DAS BIMBAS - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1060 - BAIRRO DA MASSANGARALA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1057 - PECUÁRIA - BENGUELA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 1058 - ASSEQUE - BENGUELA</option>
<option>[EQT] COMPLEXO ESCOLAR BG 1382 - BAIRRO DOS NAVEGANTES - BENGUELA</option>
<option>[EQT] MAGISTÉRIO BG 1021 - CDTE. KWENHA - BENGUELA</option>
