<option>[EQT] ESCOLA PRIMÁRIA DE ALIMUATI BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE FÁTIMA CALOMETI BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE FÁTIMA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CALAÑGE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NGUENJO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NETE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO LUPILI BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIPUTO - BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHINDEMBA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CALOMBEU BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BONGA BAILUNDO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 14 BOA VISTA BAILUNDO</option>
<option>[EQT] COLÉGIO SÃO MIGUEL DE LUVEMBA - BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CHIMBILIMA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SAMBULAIO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BAMBI BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHISSANGA - BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CAPOCO BAILUNDO</option>
<option>[EQT] COLÉGIO DO HENGUE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NAMBA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ESSAVI BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE EPANDA EVULU - BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DA BETÂNIA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHINJAMBA ELEVOCO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DA CHINJAMBA CAPIÑGALA - BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CANGUENGUE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 12 CALUEIO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAFUANGA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 2 CALANDULA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 15 OMBALA CANDIMBA BAILUNDO</option>
<option>[EQT] COLÉGIO DA MISSÃO CATÓLICA DE JANJO BAILUNDO</option>
<option>[EQT] COMPLEXO ESCOLAR CALOMBEU BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DA GANDA BAILUNDO</option>
<option>[EQT] LICEU AUGUSTO KATCHITIOPOLOLO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SÃO MIGUEL BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LUVEMBA VELHA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ETALANGALA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DA CHILALA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE DAMASCO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CANJABÃO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMULONGA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BOTA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BANGO BAILUNDO</option>
<option>[EQT] COLÉGIO EKUIKUI II DO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE UCHIA CHIMBULA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NAPICA MONTE BELO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CATUMBA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 9 VELHA CHICA CENTRO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SACHIPANGUELE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 38 DO BIMBE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE GOLONGO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO NDULO EPANDA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE DEMBA - BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CARIQUI BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 19 CAHITI BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 10 SANTA ESPERANÇA BAILUNDO</option>
<option>[EQT] COLÉGIO DO ENSINO DE ADULTOS DO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAVALA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMULUMULU BAILUNDO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DE EDUCAÇÃO DO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE UTENDE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 24 SAMORA MACHEL BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 45 DO LUNGE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE JANJO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIPANJE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAHIMBA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CHILONO BEMBUA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 4 DA MISSÃO EVANGÉLICA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SANGUA BAILUNDO</option>
<option>[EQT] COLÉGIO NGOLA DO LUNGE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHISSANGA  LUVEMBA - BAILUNDO</option>
<option>[EQT] ESCOLA P.VALVERDE - BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 18 JAMBA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO ENSINO DE ADULTOS BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHAHONGOLO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHACUMA - BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CACHIMBUELENGUE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 13 CHIMBULULO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ECANDUCO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHITUNO BAILUNDO</option>
<option>[EQT] COLÉGIO DA OMBALA MBALUNDO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 16 VELHA CHICA CAPITANGO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NGANDA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DA SANTA CRUZ BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SAILUNDO VELHO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ESPÍRITO SANTO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CALONGOLOLA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHISSEQUE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHILOMBE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHICUNDA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 30 CAUNDI BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMBONGA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ASSONGO - BAILUNDO</option>
<option>[EQT] COMPLEXO ESCOLAR N. 3 DA MISSÃO CATÓLICA DA HANGA / BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 5 SACHOLE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NOVA WAMA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHISSANJI BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHINGOMBE BAILUNDO</option>
<option>[EQT] COMPLEXO ESCOLAR DE MISSASSA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO QUINZE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 11 CANGOMBE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NGAMBOLE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LOMUNDO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DA CHITETA BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIQUENGUE - BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIPEMBE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CATUTA BAILUNDA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CATEMBO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CATANDE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CASSENGE BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CANDANDI BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BANGE CHILEWÊ BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA DA SANTA ROSA CANJABÃO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 7 CHINGOLO BAILUNDO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 6 CAFUANGA BAILUNDO</option>
