<option>[EQT] COMPLEXO ESCOLAR ÁFRICA ACHELF - COESPAA - CACILHAS HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR A.J.M LDA</option>
<option>[EQT] COMPLEXO ESCOLAR JOMAURA, VILINGA  -HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 65 DE APULI III CALIMA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR S.O.S DO CAMBIOTE, CALIMA - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº104 TCHICASSA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 1 DO SÃO PEDRO - XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] LICEU COMANDANTE VILINGA  BANDEIRA-HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 47 DO CAHULULU NZAJI - HUAMBO</option>
<option>[EQT] LICEU CATÓLICO SANTO AGOSTINHO CAPANGO HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLA PRIMÁRIA DE CATALAMBONGO S. CALIMA - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 56/ PARÓQUIA NSª SRA DE FÁTIMA CAP. HBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LOMANDA CHICULICO CALIMA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAVINDA CALIMA - HUAMBO</option>
<option>[EQT] COLÉGIO DO BOM PASTOR CACILHAS HUAMBO</option>
<option>[EQT] INSTITUTO POLITÉCNICO DE ADMINISTRAÇÃO E GESTÃO-X. SAMAC-HBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 153 DO SÃO BENTO - XAVEIR SAMACAU - HUAMB</option>
<option>[EQT] COMPLEXO ESCOLAR SÃO FRANCISCO DE ASSIS - CAMUSSAMBA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLA Nº 46 CONSTANTINO CAMOLI -CACILHAS HBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 41 DO COMPÃO BAIXO - CACILHAS HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 279 DE FREDERICO BANDEIRA-HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 177 SÃO JOÃO CALÁBIA - CAPANGO HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 285 DA CALIMA HUAMBO</option>
<option>[EQT] COLÉGIO DA CHIPIPA - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 116 DE UTALAMO VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 110 DA BOMBA ALTA VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 105 DA CHIVA - VILINGA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR MISSIO. SÃO TARCISO CALIMA - HUAMBO</option>
<option>[EQT] INSTITUTO TÉCNICO AGRÁRIO- XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA CAMATENDA  CALIMA - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 60 - BOM PASTOR CACILHAS HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHILEMBO CALIMA - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 87 DE MBUMBA YELOMBE - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 181 DE SACALAÑGE - CHIPIPA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR DO CALILONGUE DA CUCA - VILINGA HUAMBO</option>
<option>[EQT] LICEU XAVIER SAMACAU -XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR DO CASSEQUE III XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 169B DO SÃO PEDRO-XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 39 DO BOM PASTOR CACILHAS HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 69 DA ETUNDA CACILHAS HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 165 DO BENFICA COLEMBA BANDEIRA-HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 135 SANTO HENRIQUE DE OSSÓ BANDEIRA-HBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 126 FUNILEIROS BANDEIRA-HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR COMANDANTE JOAQUIM KAPANGO HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 53 DO ACADÉMICO - CAPANGO - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 36 DO CAPANGO HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR FÉ APOSTÓLICA DO SÃO JOSÉ - VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 149 DO SÃO JOÃO POPULAR VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 120 DO CRUZEIRO CALIMA HUAMBO</option>
<option>[EQT] COLÉGIO COMANDANTE DANGEREUX - CAPANGO HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE KOSITO CALIMA - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 80 DE TCHIPUIYA - CHIPIPA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 136 - ACMOL BEMFICA SANTA BANDEIRA-HUAMB</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 166 DE CAYUMBUCA - CHIPIPA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 190 DO BELO HORIZONTE - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 180 DE MANDE - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CASSEMA CALIMA - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR MISSIONARIO D. LUIS MONIV DA CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 64 DE COSSUI CALIMA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SACAHUNDO CALIMA -  HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 42 DE CACILHAS NORTE - CACILHAS HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR DEOLINDA RODRIGUES - CAPANGO HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 281 DO RAIMUNDO- XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR CIDADELA DA CRIANÇA XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 164B DA MUNDA KONGUE - XAVEIR SAMACAU-HBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 283 DO SANDJEPELE- XAVEIR SAMACAU-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 6 DO LUFEFENA - XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 175 DO CASSEQUE I- XAVEIR SAMACAU-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 52 DO CAPILONGO - CACILHAS HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 114 CAPA CHILOMBO BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 111 DO BENFICA BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 62 DA CALIMA - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NGANDAVILA CALIMA - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 85 DE NDONDO - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 77 DE CAYENJE - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 156 DO SÃO JOSÉ VILINGA HUAMBO</option>
<option>[EQT] LICEU CDTE JOAQUIM KAPANGO HUAMBO</option>
<option>[EQT] GABINETE PROVINCIAL EDUCAÇÃO DO HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 93 - MESSELE - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 83 DA BETÂNIA - CHIPIPA HUAMBO</option>
<option>[EQT] COLÉGIO 14 DE ABRIL LOSSAMBO - CACILHAS HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 82 DE LOMANDA - CHIPIPA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR SÃO LUÍS DE GONZAGA  - CAPANGO HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE VILAVI CALIMA -  HUAMBO</option>
<option>[EQT] INSTITUTO TÉCNICA DE SAÚDE BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 169A DE SAYUNGUI - XAVEIR SAMACAU-HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº4 DA MUNDA- XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 113 DO BENFICA BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 177 DE NGUNGU - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 37 DO SANTO ANTÓNIO - NZAJI - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 160 DE CASSUCULO VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 117 DA CHIVA VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 102 DO SÃO JOÃO - VILINGA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR DANIEL GOMES JUNQUEIRA BANDEIRA-HUAMBO</option>
<option>[EQT] COLÉGIO COMANDANTE BULA - CAPANGO HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR POLIVALENTE DO CUANDO CALIMA - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA CARIDADE DE JESUS CACILIAS HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR DO ENSINO ESPECIAL CAPANGO HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA 16 DE JUNHO LOSSAMBO - CACILHAS HUAMBO</option>
<option>[EQT] COLÉGIO BAPTISTA DO BENFICA BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 174 DE TCHICACA - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 100 DA LOMBIMBA CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SACACHOKO CALIMA -  HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 168 DO CALILONGUE - XAVEIR SAMACAU-HBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 162 DE NDJONGOLO- XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 9 DE CALONDEIA - XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 157 DO KAKELEWA - XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 289 DO DANGO - XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR PRINCESA DIANA NZAJI - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 55 CIDADE ALTA - CAPANGO HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 35 SÃO JOSÉ DE CLUNY - CAPANGO HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 34 AUGUSTO NGANGULA - CAPANGO HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 13 DE BABAYELA - NZAJI - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 3 DA CALOMANDA NZAJI - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NGULAWA CALIMA -  HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO 1º DE MAIO - MUENESSI - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA ADULTOS DO SÃO JOÃO - VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 142 DO SÃO JOSÉ VILINGA HUAMBO</option>
<option>[EQT] ESCOLA DE MAGISTÉRIO - ADPP - XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAPUTO CALIMA - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR MISSIONÁRIO DOM BOSCO BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA POLITÉCNICA - ADPP - XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 78 DA CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 176 DE TCHILONGA - CHIPIPA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR AMIZADE ANGOLA - CHINA LOSSAMBO HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MALANGA CALIMA - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BOA VISTA DE UTALAMO - VILINGA HUAMBO</option>
<option>[EQT] COLÉGIO DR. ANTÓNIO AGOSTINHO NETO - VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 2 DO KALUNDO- XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº10 DO PETRÓLEO- XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 144 DA CAMUNDA BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 145 DO BENFICA BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 140 DA SANTA TERESA BANDEIRA-HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 134 SANTA CRUZ CANHE BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 54 / 28 DE AGOSTO BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 285 DO CALUEYO VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 109 DA VILA GRAÇA - VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 107 DA CHIANGA - VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 106 DA CHIVA - VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 104 DO CAMBIOTE CALIMA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 103 DO SÃO JOÃO - VILINGA HUAMBO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO HUAMBO</option>
<option>[EQT] ESCOLA DE MAGISTÉRIO FERRAZ BOMBOCO BANDEIRA-HUAMBO</option>
<option>[EQT] LICEU 22 DE NOVEMBRO - LOSSAMBO - CACILHAS HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIWAYA CALIMA - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 166 DA MUNDA PAIVA - XAVEIR SAMACAU-HBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 81 DE COPONGO - CHIPIPA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR LAR DOS PEQUENINOS - CAPANGO HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SILANJALA CALIMA - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR PAIVA DOMINGOS DA SILVA - VILINGA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 155 DA MUNDA PAIVA XAVEIR SAMACAU - HUAM</option>
<option>[EQT] ESCOLA DE MAGISTÉRIO - ICRA - NZAJI - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 108 DO MACOLOCOLO BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 291 DA BOMBA BAIXA VILINGA HUAMBO</option>
<option>[EQT] COLÉGIO NOÉ NDEUTAPO LUTERANA BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 163 DE KALIKOKE- XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 169 DO CAVONGUE LOSSAMBO - CACILHAS HBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 48 DO CAPANGO HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 44 DO NGONGOINGA NZAJI - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 73 DE CAPIÑGALA CALIMA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR SÃO FRANCISCO DE ASSIS -F. QUISSALA-X. S.HB</option>
<option>[EQT] COLÉGIO DA CHIVA - VILINGA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 86 DE TCHANGUILI - CHIPIPA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR ANTIGOS COMBATENTES E VETERANOS DA PÁTRIA - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 5 DA AVIAÇÃO NZAJI - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 161 DO CALUNDO - XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 282 DE NDENDE - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 101 DE CANJILI - CHIPIPA HUAMBO</option>
<option>[EQT] COLÉGIO COMANDANTE NZAJI - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAHILI CALIMA - HUAMBO</option>
<option>[EQT] COLÉGIO FERRAZ BOMBOCO -  XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 167 DE CANDIMBA BANDEIRA-HUAMBO</option>
<option>[EQT] COLÉGIO 4 DE FEVEREIRO - PETRÓLEO - XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 7 DO BELÉM DO - XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 284 DO CALOMBRINGO - XAVEIR SAMACAU-HBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 164A DA CHIVELA -XAVEIR SAMACAU - HUAMBO</option>
<option>[EQT] ESCOLA PRIMARIA DO ENSINO DE ADULTOS DE CACILHAS HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR SANTA TERESINHA - CAMUSSAMBA CACILHAS HBO</option>
<option>[EQT] ESCOLA PRIMARIA DO ENSINO DE ADULTOS DO BENFICA BANDEIRA-HBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 158 DE MACOLOCOLO BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 128 - CARDOSO BANDEIRA-HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 151 DO CAPANGO HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 280 DO CAVONGUE BAIXO - NZAJI - HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº244 VILA SECA ESPARZA NZAJI - HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 84 DE CATCHACA - CHIPIPA HUAMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 161 DO SANTO AMARO VILINGA HUAMBO</option>
<option>[EQT] COMPLEXO ESCOLAR REI LIVONGUE - XAVEIR SAMACAU - HUAMBO</option>
