<option>[EQT] ESCOLA PRIMÁRIA DE DOMBODOLA</option>
<option>[EQT] MAGISTÉRIO REI HAIMBILI-YA-HAUFIKU - XANGONGO</option>
<option>[EQT] INSTITUTO TÉCNICO DE SAÚDE  MADRE ISABEL DO CHIULO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIVEMBA - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TCHICOLOSSOTA - HUMBE</option>
<option>[EQT] COMPLEXO ESCOLAR DO PEU-PEU - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA 11 DE NOVEMBRO - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OLUTULA I - OMBALA-YO-MUNGU</option>
<option>[EQT] COMPLEXO ESCOLAR REI SHIHETEKELA - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MPUIKITI - MUCOPE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMATENDE - NAULILA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CATEQUERO - MUCOPE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONAMIDI - OMBALA-YO-MUNGU</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ONASSALAMBA MARCO 12,5 - OMBALA-YO-MUNGU</option>
<option>[EQT] COMPLEXO ESCOLAR PADRE JOSÉ M.V.B FELGUEIRAS - OMBALA-YO-MUN</option>
<option>[EQT] ESCOLA PRIMÁRIA CANÍSIO HANDJELE - XANGONGO</option>
<option>[EQT] LICEU PADRE TOMÁS DA MISSÃO CATÓLICA DO CHIULO</option>
<option>[EQT] INSTITUTO POLITÉCNICO DOUTOR ANTÓNIO DIDALELWA - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TCHOLOMBOTU - NAULILA</option>
<option>[EQT] COMPLEXO ESCOLAR DE MAHENGUE-A-MUKULU - HUMBE</option>
<option>[EQT] COMPLEXO ESCOLAR VAU-DO-PEMBE - XANGONGO</option>
<option>[EQT] COLÉGIO DO CHIULO - MUCOPE</option>
<option>[EQT] COMPLEXO ESCOLAR DR. MARTINHO LUTERO - XANGONGO</option>
<option>[EQT] COMPLEXO ESCOLAR DE OMBALA YO MUNGU - SEDE</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DE EDUCAÇÃO DE OMBADJA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE KANKOMBO - MUCOPE</option>
<option>[EQT] COMPLEXO ESCOLAR SIMIONE MUKUNE - XANGONGO</option>
<option>[EQT] COMPLEXO ESCOLAR DE KAPANDA - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NDIMBA-TCHIHOLO - HUMBE</option>
<option>[EQT] COMPLEXO ESCOLAR REI LUHUMA DE MANKHETE - MUCOPE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MANAMBONDE - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA AUGUSTO NGANGULA - XANGONGO</option>
<option>[EQT] COMPLEXO ESCOLAR DE NAULILA</option>
<option>[EQT] COLÉGIO NAHOLO-YA-HAIVINGA - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHICA-SEDE - MUCOPE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TCHILAU - MUCOPE</option>
<option>[EQT] COMPLEXO ESCOLAR BEATRIZ MUKWASIFA DE SHIETEKELA - NAULILA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMULUNGA MARCO 10 - OMBALA-YO-MUNGU</option>
<option>[EQT] COMPLEXO ESCOLAR MAXIMILIANO OCTÁVIO DA SILVA - HUMBE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OLUTUNDA - HUMBE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MUJOMBE - MUCOPE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIPEKE - NAULILA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OUPALE - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NAMUKULUNGU - HUMBE</option>
<option>[EQT] COMPLEXO ESCOLAR DE CALUEQUE - NAULILA</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SANTA TERESINHA - MUCOPE</option>
<option>[EQT] COMPLEXO ESCOLAR MUCOPE SEDE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE KAULAPEPO - HUMBE</option>
<option>[EQT] ESCOLA PRIMÁRIA 4 DE FEVEREIRO - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMENYE - OMBALA-YO-MUNGU</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MATUKU - MUCOPE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LUHENGUE - HUMBE</option>
<option>[EQT] COMPLEXO ESCOLAR DE ONEPOLO - OMBALA YO MUNGU</option>
<option>[EQT] ESCOLA PRIMÁRIA DE KAFÚ - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LUPEMBE - HUMBE</option>
<option>[EQT] COMPLEXO ESCOLAR DO DAMEQUERO - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº1 DO CHIULO - MUCOPE</option>
<option>[EQT] ESCOLA PRIMÁRIA DE KANKONDA - NAULILA</option>
<option>[EQT] COMPLEXO ESCOLAR DE OMUFILU - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA MÁRIO SAUMBWAKO - XANGONGO</option>
<option>[EQT] COMPLEXO ESCOLAR OMUANDI WAKAMBABA - XANGONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NKUMBI YANDJILI - MUCOPE</option>
