<option>[EQT] ESCOLA PRIMÁRIA DE CHACUMA ALTO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAWALA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CENTRO NDUMBO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIQUENGUE -CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 8  DO BAIRRO 27 - CACHIUNGO</option>
<option>[EQT] COLÉGIO DE UPUNDA - CACHIUNGO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DE EDUCAÇÃO DE CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAWEIE CACHIUNGO</option>
<option>[EQT] COLÉGIO DE SAHEMBA CACHIUNGO</option>
<option>[EQT] COLÉGIO DO ALTO CHIUMBO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE OMBALA MOMA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE FUNDA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMUENHO - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BUNJO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CENTRO CAUALA - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHISSUMBA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMBUIO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMBIA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 9 NONDOLO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 17 CHIUMBO CACHIUNGO</option>
<option>[EQT] LICEU DO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SAQUELEMA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LUAIA ALDEIA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE ETUNDA MOMA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAVIPI CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CASSOMA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAIUMBA CACHIUNGO</option>
<option>[EQT] COLÉGIO Nº 7 GOMES CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CANHANGA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA JIMBI - CACHIUNGO</option>
<option>[EQT] INSTITUTO POLITÉCNICO DO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SACHIPANGUELE CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SAPATO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SACHIPOCO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NUNDA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 31 SAVITANGAIALA - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MOMBOLO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 23 NAMBAMBI CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA CUTACALA - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA CHIPANDO - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CATA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SACHOIA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SACHILOMBO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LUAIA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMARIA DO ENSINO DE ADULTOS CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 10 SANTA ANA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 1 FÁTIMA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CALUNDA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LÓMUE I E II CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SAWALA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 5 DE SANTARÉM CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº2 SOUSA-ALTA CACHIUNGO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAHUQUE CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE BOA ESPERANÇA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CASSESSE CACHIUNGO</option>
<option>[EQT] COLÉGIO DE SAVITANGIALA CACHIUNGO</option>
<option>[EQT] COMPLEXO ESCOLAR DE VAVAYELA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SANGONGA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SAHUMBA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIMBANDUA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 18 CACHILENGUE CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE UPUNDA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NGANJI CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NDUMBA CACHIUNGO</option>
<option>[EQT] COMPLEXO ESCOLAR DA CHINHAMA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 12 CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE MUNDOMBA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMELA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIPACA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 8 VINTE E SETE CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMAMA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CALIUEQUE CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA CHILENDA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHIANGA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SASSOMA - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LOMBAMBO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº  26 CHINHAMA - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº15 CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE UTANHA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DA MISSÃO - CAVANGO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SACAPATA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE JAMBA -CHINHENI CACHIUNGO</option>
<option>[EQT] COLÉGIO MARIA DA SILVA NETO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 22 CHIVINDA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 19 CHAMUANGA - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAMUENGUE CACHIUNGO</option>
<option>[EQT] COMPLEXO ESCOLAR DA MISSÃO DO DONDI CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA - SASSANGO - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE NAPICA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 28 DE ALTO CHIUMBO CACHIUNGO</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 14 - TERESIANA - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SOMA NDUMBO - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHINDONGA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CHICULUNDUNDA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE SALUPEMBE CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CAVANGO ALDEIA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE VITATO - CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 13 CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LONUNDO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 7 GOMES CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CASSETECO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA DE CALILONGUE CACHIUNGO</option>
<option>[EQT] COLÉGIO DE NDUNDUMA CACHIUNGO</option>
<option>[EQT] COLÉGIO DO CHIUMBO CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 30 SAHEMBA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 21 DA ALDEIA DE SANGANGUELA CACHIUNGO</option>
<option>[EQT] ESCOLA PRIMÁRIA Nº 20 JIMI CACHIUNGO</option>
