<option>[EQT] ESCOLA PRIMÁRIA BG 6098 - LUMBO - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG  6088 - CANOQUELA - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6086 - UKONGO I E II - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6055 - CHISSEQUELE - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6005 - CANDUNDO - BALOMBO</option>
<option>[EQT] MAGISTÉRIO BG 6037 - BALOMBO </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6066 - REV. GASPAR VANHALE - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6000 - VALÓDIA - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6050 - NJINGA MISSÃO - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6010 - CAÁLA - BALOMBO</option>
<option>[EQT] COLÉGIO BG 6017 - 17 DE SETEMBRO - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6097 - LOMETI - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6095 - NGOLO I - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6087 - CAFÍNDUA - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6085 - CAMBANDJO - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6073 - CHIQUELÊ - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6067 - STA. TERESA MENINO JESUS - BALOMBO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 6074 - CASACO - BALOMBO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 6003 - DR. ANTÓNIO AGOST. NETO - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6052 - CHICO DA WAITH - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6041 - CHICONGUELE - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6022 - 22 DE NOVEMBRO - BALOMBO</option>
<option>[EQT] INSTITUTO POLITÉCNICO BG 6033 - BALOMBO </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6060 - REI MANDUME - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6058 - LIBATA - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6032 - ANGOLA - CUBA - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6013 - CHIMBONDO - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6009 - CAYENGUE - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6007 - HUNGULO - BALOMBO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6016 - CHICÚLIA - BALOMBO</option>
<option>[EQT] LICEU BG 6002 - BALOMBO </option>
<option>[EQT] COMPLEXO ESCOLAR BG 6065 - SÃO VICENTE DE PAULO - BALOMBO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 6091 - CHINDUMBO - SEDE - BALOMBO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 6053 - MAKA-MOMBOLO - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6096 - KANGUMBE I E II - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6089 - CAVÍNCIA - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6084 - CACHIMBITI - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6063 - HANGA - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6054 - CANJALA - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6042 - LONGONGO - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6008 - CAPANGO - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6093 - AMELÃ - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6072 - CAPONTE - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6038 - NHANHÃ-NDULÃ - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6015 - BUNGUE - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6011 - CALUÍTA - BALOMBO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 6001 - EKUIKUI II - BALOMBO</option>
