<option>[EQT] ESCOLA PRIMÁRIA N. 43 TXIPENGUE CAIUMA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 40 JOAO BAPTISTA PATRICIO</option>
<option>[EQT] COLEGIO N. 42 MUCUNGA SANDA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 45 SACAMANA MAKALO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 44 PASCOAL CALEMBA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 39 PAULO GOMES</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 38 LUVULU SANAMA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 41 LEONARDO CHINGA</option>
<option>[EQT] ESCOLA PRIMARIA N. 35 HOJE - YA - HENDA</option>
<option>[EQT] ESCOLA PRIMARIA N. 32 JOAQUIM CARDOSO JAQUINDA</option>
<option>[EQT] ESCOLA PRIMÀRIA N. 1 4 DE ABRIL</option>
<option>[EQT] ESCOLA PRIMÀRIA N. 10 ZANGO</option>
<option>[EQT] ESCOLA PRIMARIA N. 19 LIBERDADE</option>
<option>[EQT] ESCOLA PRIMARIA N. 15 AGOSTINHO MENDES CARVALHO</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 36 16 JUNHO</option>
<option>[EQT] ESCOLA PRIMARIA N. 30 DR. ANTONIO AGOSTINHO NETO</option>
<option>[EQT] ESCOLA PRIMARIA N. 03 ANTIGOS COMBATENTE</option>
<option>[EQT] ESCOLA PRIMARIA N. 22 COMADANTE VALODIA</option>
<option>[EQT] ESCOLA PRIMARIA N. 25 10 DE DEZEMBRO</option>
<option>[EQT] ESCOLA PRIMARIA N. 24 11 DE NOVEMBRO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE MUCONDA</option>
<option>[EQT] ESCOLA PRIMARIA N. 6 ASTIDES CADETE KIMA KENDA</option>
<option>[EQT] MAGISTÉRIO N. 38 CERTEZA MUCONDA</option>
<option>[EQT] COLÉGIO CHINGULI N. 37 MUCONDA</option>
<option>[EQT] ESCOLA PRIMARIA N. 26 1 DE DEZEMBRO</option>
<option>[EQT] ESCOLA PRIMÀRIA N. 28 1 DE MAIO</option>
<option>[EQT] ESCOLA PRIMARIA N. 17 AUGUSTO NGANGULA</option>
<option>[EQT] ESCOLA PRIMARIA N. 34 MARIA EUGENIA NETO</option>
<option>[EQT] ESCOLA PRIMARIA N. 07 DEOLINDA RODRIGUES</option>
