<option>[EQT] ESCOLA PRIMÁRIA BG 7055 - CHIMBUNGO - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7004 - 22 DE NOVEMBRO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG - 7003 - 25 DE ABRIL - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7142 - CAMELÃ - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7134 - CHIVANGULULA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7118 - EKUNGO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7115 - LOSSINJA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7100 - CHINDIANDIA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7087 - CHINDEMBA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7048 - CHICUMA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7010 - 4 DE FEVEREIRO - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7052 - UNGONGO - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7018 - RAINHA NJ. MBANDI - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7001 - PAIVA D. DA SILVA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7143 - ALTO HENRIQUE - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7125 - LUCUNGA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7097 - CAVINDA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7091 - CALUVANGO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7081 - BALAMBI - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7060 - MUNJOMBA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7049 - LOHOMBO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7045 - CANGOMBE - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7040 - DE ISSAKA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7032 - CAISSOMBO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7025 - AUGUSTO NGANGULA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7009 - 11 DE NOVEMBRO - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7047 - 4 DE JANEIRO - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7037 - CAVIMBI II - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7027 - 27 DE MARÇO - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7019 - EKUIKUI I - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7314 - SEDE MONTE BELO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7139 - JUMBA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7127 - CHICONGUELE - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7026 - MISS. VINCENZO MONTANARO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7102 - CHITOMBE - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7096 - NGUALI - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7084 - ALTO MORRO - BOCOIO</option>
<option>[EQT] CENTRO DE RECURSO BG 7146 - EDUCAÇÃO ESPECIAL - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7021 - CHIMBA - BOCOIO</option>
<option>[EQT] LICEU BG 7000 - BOCOIO </option>
<option>[EQT] INSTITUTO TÉCNICO DE SAÚDE BG 7145 - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7029 - DUMBO - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7014 - EKUIKUI II - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7114 - ALTO PUNDO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7104 - CHIMBUITITI - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7094 - DE CUBAL COYAYA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7085 - LONJAMBA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7059 - SACUTOPI - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7057 - MANGA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7043 - CUHÚLA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7034 - CAVIMBI I - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7028 - MUTU-YA-KEVELA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7022 - CHINDURI - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7020 - CANGOIA -BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7007 - 4 DE ABRIL - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7058 - LOSSONGA - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7113 - PASSE - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7106 - ISSOMBO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7077 - MESSALO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7067 - CHINGUNDO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7005 - 16 DE JUNHO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7011 - 10 DE DEZEMBRO - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7103 - DR. ANTÓNIO A. NETO - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7110 - UNGOMBO - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7024 - CDTE CASSANJI - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7137 - ZUARTE - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7120 - EYOVE - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7073 - BELINO BASTOS - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7071 - SEQUETA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7061 - DR. FREITAS - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7031 - LOMOLÕ - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7017 - DR. ANTÓNIO A. NETO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7133 - NGANDO AWEKO - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7128 - CAQUIM - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7123 - LUVALE - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7116 - NGOA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7107 - LOMAMA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7089 - SAIDY VIEIRA MINGAS - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7063 - CAÁLA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7012 - ETUNDA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7015 - 8 DE MARÇO - BOCOIO</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7076 - TOLA - BOCOIO</option>
<option>[EQT] COMPLEXO ESCOLAR BG 7065 - SARAIVA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7044 - AGRO VILA - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7136 - CASSEQUE - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7054 - LONENGUE - BOCOIO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 7008 - CDTE GIKA - BOCOIO</option>
<option>[EQT] COLÉGIO BG 7002 - REI MANDUME - BOCOIO</option>
