<option>[EQT] ESCOLA PRIMÁRIA BG 4242 - MARCO ESTAÇÃO- CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4206 - GOIO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4215 - KAKUTI - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4157 - KALUPULI - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4219 - KAIPUNDA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4211 - KALEA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4039 - KANHELELA ALTA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4236 - KAPUNGU - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4176 - CAIPUMBA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4216 - KAITALA - CUBAL</option>
<option>[EQT] ESCOLA PRIMARIA BG 4047 - LOSSINJA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4140 - KATALA-CAVISYA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TCHIMBIONGO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4191 - SIPITI - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4077 - LONDJOMBELE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4029 - AUGUSTO NGANGULA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TCHILIVA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4151 - TCHENGUETI - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4213 - TCHAMBUNGU - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4202 - UPINDI - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA DE KOSOLO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4222 - KAKELEWE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4088 - NDUVU - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4135 - KAMBINDJI - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4025 - TCHIPEYO 2º - CUBAL</option>
<option>[EQT] INSTITUTO TÉCNICO DE SAÚDE BG 4195 - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR  BG 4070 - CAMBONDONGOLO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4010 - EKUIEKUI II - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR BG 4159 - CAPUPA - CUBAL</option>
<option>[EQT] COLÉGIO BG 4113 - TUMBULO SEDE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4034 - HENGA - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR BG 4016 - TERESIANA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4048 - LUNDA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4050 - PATRICIE LUMUMBA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4040 - GARCIA NETO N.º 40 - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4198 - VAVAYELA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4149 - UTALALA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4201 - LUKUNHO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4208 - KATCHIKELA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4091 - KATATEKA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4154 - KATAPI - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4049 - MASSACRE DE QUIFANGONDO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4042 - TCHISSELEHÂ - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA DE LUKUMBI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4096 - CASSORIO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4153 - KALONDJAVA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4203 - KALOMOLO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4064 - KAHELEKETE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4097 - LOMUPA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4046 - CDTE KWENHA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4053 - RIO BOM - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4018 - YAKANEKAVA - CUBAL</option>
<option>[EQT] ESCOLA TÉCNICA AGRÁRIA BG 4197 - ALTO KAPACA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4022 - 1º DE MAIO - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR BG 4076 - ATIOPO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4112 - ALTO TCHILENGA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4217 - LAGO-BOM - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4038 - KANIANDUTI - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4062 - KALOMBANDA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4080 - NGONDE II - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4224 - LONGOLE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4111 - KAYENDJE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4193 - KANGUNDA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4214 - KAIKUYU - CUBAL </option>
<option>[EQT] COMPLEXO ESCOLAR BG 4100 - LOMAUM - CUBAL</option>
<option>[EQT] ESCOLA  PRIMÁRIA BG 4028 - ARAME TUNEL - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4026 - 8 DE MARÇO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4164 - LUTILA WEMBA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4199 - KAVOMBWE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4205 - BARRAGEM DO DUGO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4020 - 2 DE MARÇO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4166 - TCHIKWA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4042 - REI MANDUME - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4165 - TCHINDJAMBA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4123 - KANDJUMBA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4065 - CAMBONDONGOLO FAZENDA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4138 - 4 DE JANEIRO - CUBAL</option>
<option>[EQT] INSTITUTO POLITÉCNICO BG 4196 - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4017 - TOMÁS FERREIRA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4024 - 4 DE FEVEREIRO - CUBALO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4036 - DEOLINDA RODRIGUES - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4004 - 20 DE JUNHO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4063 - 73ª BRIGADA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4058 - 16 DE JUNHO- SALA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4204 - SAGRADA ESPERANÇA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4054 - TCHIPAKO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4234 - SIMBOLIA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4092 - SAMANDE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4086 - KASALASITU - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4181 - KALONDALA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4209 - NDUMA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4087 - TCHIVOLE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4152 - KUPA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4212 - HENGUE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA DE TCHITIAKUMA</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4142 - TCHALITYAÑGA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4226 - KAISSOMBO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4078 - CHIMBOA DA HANHA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4158 - KATCHIQUELA - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR BG 4233 - KAHANGA-MALONGO - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR BG 4056 - VACARIA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4043 - KAMUNDA QUISSOLO - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR BG 4033 - LASSALETE - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR  BG 4015 - SÃO PAULO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4229 - TUMBULO SEDE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4044 - KATAMBA - CUBAL</option>
<option>[EQT] COLÉGIO BG 4013 - KILAMBA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4230 - ENGRACIA JAMBA- MISSÃO - CUBAL </option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4007 - CDTE  JIKA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4003 - 1º DE JUNHO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4014 - LUCRÉCIA PAIM - CUBAL</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4072 - 5 DE OUTUBRO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4079 - TCHIQUEQUE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4182 - KAVIÃLÃ - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4192 - KAFILILI - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4051 - PEDRO DE C. VAN-DÚNEN LOY - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4186 - NAMBA KALEA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4067 - CALANDA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4066 - ELAVELO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4218 - KALUMWE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4231 - CAIMBOVO I - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4228 - CDTE KUSSI  LOMAUM - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4121 - PUHONA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4167 - ONAMANO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4104 - SOPE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4000 - 10 DE DEZEMBRO - CUBAL</option>
<option>[EQT] MAGISTÉRIO BG 4011 - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4189 - KAYANDI - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR EKUIKUI II</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4045 - KAVILUMBA - CUBAL</option>
<option>[EQT] ESCOLA  PRIMÁRIA BG 4027 - AGOSTINHO NETO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4021 - 1º DE AGOSTO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4009 - CDTE KASSANJE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4008 - CDTE BULA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4006 - CÁRITAS - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4210 - TCHILUNDA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4200 - TCHIYLOLYO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4083 - KAYOMBE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4207 - KALOHANDA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4117 - LULAMBO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4099 - LAVELO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4041 - KALONENGUE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4194 - KAIPEPE - CUBAL</option>
<option>[EQT] LICEU BG 4235 - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4061 - BUNDIANGOLO-LUHENGUE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA DE VIA SERRAÇÃO</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4168 - LOHALA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4105 - BANJA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4057 - JEREQUETE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4005 - 27 DE MARÇO - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR BG 4147 - LONETA-HALO - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR BG 4031 - CASSIVA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4019 - 14 DE ABRIL - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4002 - 17 DE SETEMBRO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4023 - 4 DE ABRIL - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4190 - SONGUE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4094 - KAÑGELE - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4118 - KALIAMUMA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4059 - UTUMBA BAIXO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4055 - TUMBA TERRA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4095 - KATEYA-MATEMBA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4101 - LUCUIO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4220 - KONGA - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4068 - KALOHOMBO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4150 - TUMOLO SEDE - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR BG 4082 - YAMBALA - CUBAL</option>
<option>[EQT] COMPLEXO ESCOLAR BG 4032 - CDTE CUSSI - CUBAL</option>
<option>[EQT] COLÉGIO BG 4012 - ILÍDIO MACHADO - CUBAL</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 4001 - 11 DE NOVEMBRO - CUBAL</option>
