<option>[EQT] ESCOLA PRIMÁRIA BG 9021 - LOMALACA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9040 - LAVELO - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR  BG 9084 - LONDANGANGA - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR BG 9098 - SENJE - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9093 - TCHILUI - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9033 - VIHELETETE - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9011 - CAVALOÑGA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9057 - LUMBILI - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9103 - HETALA - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR BG 9050 - CUTEMBO - CHONGOROI</option>
<option>[EQT] COLÉGIO BG 9016 - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR BG 9047 - CHÓ - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9029 - TÚWE - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9089 - TCHITETA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9068 - SONDONDO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9102 - VANDOMBE II - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA  BG 9014 - CAWONGO II - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR BG 9059 - MISSÃO DE MALONGO  - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9032 - VIANJA - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR BG 9006 - CAMBANDI I - CHONGOROI</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DO CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9041 - MUTEPILA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9053 - KATCHIPATINHO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9063 - UPINDE - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9060 - KAMOÑGA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9048 DE CUTEMBO EMBALA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9051 - HENGUE NDOVA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9104 - BOLONGUELA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9092 - MUSSOLO CAMUVI - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR BG 9001 - ANGOLA LIVRE - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR BG 9005 - DEOLINDA RODRIGUES - CHONGOROI </option>
<option>[EQT] COMPLEXO ESCOLAR BG 9052 - M. S. PAULO-MUNDJOMBUE- CHONGOROI</option>
<option>[EQT] LICEU BG 9017 - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9045 - YUVO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9008 - CALUSSIPA I - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9003 - CALILONGUE - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9015 - CAYUNDI - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9099 - TCHITOCO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9023 - TACA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9079 - CAVISSECUA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9073 - TCHELEKELA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9071 - BUNJEI I - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9062 - NDUNGULA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9088 - BONDONGOLO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9082 - KATELELÃ - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9012 - CAVINGIRITE - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9069 - VAIVA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9067 - TCHINOÑGUA - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR BG 9313 - HANJA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9083 - KAYOA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9030 - KATCHIMANO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9042 - NHAÑGA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9081 - CALOMANDA II - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9002 HOJI -YA -HENDA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9024 - TCHITATA I - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9010 - CAMAIA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9078 - ASSAVETO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9028 - CAMUCUIO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9080 - CAIMBULÃ - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9054 - APITO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9105 - CAVISSAMBA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9106 - LONDANGANGA - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR BG 9034 - VINAMA - CHONGOROI</option>
<option>[EQT] COMPLEXO ESCOLAR BG 9036 - CUI SEDE - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9217 - MALONGO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9074 - CAMUINE BAIXO - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA  BG 9400 - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9101 - YAMBA - CHONGOROI</option>
<option>[EQT] ESCOLA PRIMÁRIA BG 9007 - CAMBANDI II - CHONGOROI</option>
