<option data-provincia="Malanje">Massango</option>
<option data-provincia="Malanje">Marimba</option>
<option data-provincia="Malanje">Calandula</option>
<option data-provincia="Malanje">Cahombo</option>
<option data-provincia="Malanje">Kiwaba Nzoji</option>
<option data-provincia="Malanje">Cacuso</option>
<option data-provincia="Malanje">Quela</option>
<option data-provincia="Malanje">Malanje</option>
<option data-provincia="Malanje">Mucari</option>
<option data-provincia="Malanje">Cangandala</option>
<option data-provincia="Malanje">Cambundi-Catembo</option>
<option data-provincia="Malanje">Luquembo</option>
<option data-provincia="Malanje">Kunda Dya Baze</option>
<option data-provincia="Malanje">Quirima</option>
