<option>[EQT] COMPLEXO ESCOLAR COMISSÁRIO NGONGO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 1º DE DEZEMBRO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA SOBA KITACAFUCA KM 70 - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 22 DE NOVEMBRO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA PAROQUIAL NOSSA SENHORA DA GRAÇA - P. AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO MUSSONGA - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CHIETO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA CAZUA BLOCO II - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA EKUIKUI II - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA COMISSÁRIO SEMBO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 14 DE ABRIL - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA EDUARDO BONDO - PORTO AMBOIM</option>
<option>[EQT] COMPLEXO ESCOLAR EUSÉBIO DE BRITO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA CAZANGA - PORTO AMBOIM</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DE EDUCAÇÃO DE PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 336 - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA CHOL - CHOL - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO BAIRRO CATOLO - DENDA PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO BAIRRO CASSANGE - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA AUGUSTO NGANGULA - PORTO AMBOIM</option>
<option>[EQT] COMPLEXO SÃO JOÃO PAULO II - PORTO AMBOIM</option>
<option>[EQT] COLÉGIO 4 DE ABRIL - PORTO AMBOIM</option>
<option>[EQT] MAGISTÉRIO DE PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CAPOLO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 21 DE MARÇO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 17 DE SETEMBRO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA HULU AZOMBO KAJIMBO - CARIOTA PORTO AMBOIM</option>
<option>[EQT] COMPLEXO ESCOLAR JOSÉ SABINO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CALELE - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO BAIRRO DA LILA - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DA CASA BRANCA - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO KM 11 - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA CHÉ GUEVARA - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CASSELEMBE - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO CAMBALO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 1 DE JUNHO - PORTO AMBOIM</option>
<option>[EQT] LICEU VIRIATO DA CRUZ - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 4 DE JANEIRO - CASSUADA - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA 4 DE FEVEREIRO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA SUMBA PUNGUILA LUANGONGO KM 28 - P.AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA JOAQUIM BONDO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA DO BAIRRO MULEMBA - NGOLA LOMBO  - P. AMB</option>
<option>[EQT] LICEU DO TANGO - PORTO AMBOIM</option>
<option>[EQT] ESCOLA PRIMÁRIA INACIO FRAGOSO - PORTO AMBOIM</option>
