<option>[EQT] ESCOLA PRIMÁRIA N. 4 - BUACA - CALANDULA</option>
<option>[EQT] ESCOLA PRIMÁRIA DO HELE-PESO - CALANDULA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 20 - MISSÃO CATÓLICA - CALANDULA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 17 - 4 DE JANEIRO - CALANDULA</option>
<option>[EQT] COMPLEXO ESCOLA N. 16 - 22 DE NOVEMBRO - CALANDULA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 15 - 17 DE SETEMBRO - CALANDULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 9 - TANQUE - CALANDULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 8- GONGO- CALANDULA</option>
<option>[EQT] COMPLEXO ESCOLA N. 13 - 11 DE NOVEMBRO - KATECO KANGOLA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 6 - MATOMBE - CALANDULA</option>
<option>[EQT] COLÉGIO N. 11 - 4 DE FEVEREIRO - CALANDULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 5 - RAINHA NGINGA MBANDE - CALANDULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 10 - VULA BONGO - CALANDULA</option>
<option>[EQT] LICEU N. 12 - 2 DE SETEMBRO - CALANDULA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE CALANDULA </option>
<option>[EQT] COMPLEXO ESCOLAR N. 14 - CAXITO- CALANDULA</option>
<option>[EQT] COMPLEXO ESCOLAR Nº 19 NGOLA KILUANJE - CALANDULA</option>
<option>[EQT] DIRECÇÃO MUNICIPAL DA EDUCAÇÃO DE CALANDULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 1 - PIPA - CALANDULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 18 - HOJI YA HENDA - CALANDULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N.3 -  AMARAL - CALANDULA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 2 - 1º DE MAIO - CALANDULA</option>
