<option>[EQT] MAGISTÉRIO 1251 NJAMBELWA KATEINE</option>
<option>[EQT] MAGISTÉRIO N. 1851 - TACA HUMPATA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 692 - RUIVAL </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 691 - PROJECTO NOSSA TERRA </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 95 - PIONEIRO ZECA </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 697 - NTAMANA </option>
<option>[EQT] INSTITUTO TÉCNICO AGRÁRIO N. 702 - TCHIVINGUIRO</option>
<option>[EQT] ESCOLA N. 65 - AUGUSTO NGANGULA </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 1102 - KANGOLO </option>
<option>[EQT] ESCOLA PRIMÁRIA HEVA - HUMPATA</option>
<option>[EQT] ESCOLA PRIMÁRIA ASSOCIAÇÃO 11 DE NOVEMBRO - HUMPATA</option>
<option>[EQT] ESCOLA PRIMÁRIA NDJAMBI - HUMPATA</option>
<option>[EQT] ESCOLA PRIMÁRIA  N. 1110 - HONGO AMÉRICO BOA VIDA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 351 - ESTAÇÃO ESPERIMENTAL AGRICOLA </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 466 - ONKULUVALA </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 551 - BATA - BATA</option>
<option>[EQT] COMPLEXO ESCOLAR N. 184 - AO CAMPO </option>
<option>[EQT] ESCOLA PRIMÁRIA PALANCA II - HUMPATA</option>
<option>[EQT] DIRECÇAO MUNICIPAL DA EDUCAÇAO DA HUMPATA</option>
<option>[EQT] COLÉGIO N. 698 - HUMPATA </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 221 - COMANDANTE COW BOY </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 229 - KAPANDEIO </option>
<option>[EQT] LICEU N. 700 - HUMPATA</option>
<option>[EQT] ESCOLA PRIMÁRIA PALANCA I - HUMPATA</option>
<option>[EQT] ESCOLA PRIMÁRIA N. 695 - TCHIHANHINA </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 1161 - TACA </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 21 - LEBA </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 693 - TCHANGALALA </option>
<option>[EQT] ESCOLA PRIMÁRIA KAHOLO - HUAMPATA</option>
<option>[EQT] INSTITUTO POLITÉCNICO N. 699 - DA HUMPATA </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 27 - ALTO BIMBI </option>
<option>[EQT] ESCOLA PRIMÁRIA N. 222 - ESTAÇÃO ZOOTECNICAS </option>
